using ToscaArtifactAutomation.Core.Canonical;

namespace ToscaArtifactAutomation.PLDC.CanonicalMaps;

public static class SmokeTestAutoCanonicalMap
{
    public static IReadOnlyList<CanonicalAction> ClientAndAccount { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0012:0001",
            Sequence = 1,
            SourceStep = "0012",
            SourceName = "Click on New Quote button",
            SourceXTestStep = "3a19dd55-d443-6b95-2414-e782dd27e3e3",
            SourceSentence = "I wait until \"Btn_New Quote\" exists",
            Module = "EQ||New Quote",
            Operation = CanonicalOperation.Wait,
            Target = "Btn_New Quote",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0012:0002",
            Sequence = 2,
            SourceStep = "0012",
            SourceName = "Click on New Quote button",
            SourceXTestStep = "3a19dd55-d443-6b95-2414-e782dd27e3e3",
            SourceSentence = "\"Btn_New Quote\" should equal \"New Quote\"",
            Module = "EQ||New Quote",
            Operation = CanonicalOperation.Verify,
            Target = "Btn_New Quote",
            ValueExpression = "",
            ExpectedExpression = "{{data:expected_btn_new_quote_2}}",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0012:0003",
            Sequence = 3,
            SourceStep = "0012",
            SourceName = "Click on New Quote button",
            SourceXTestStep = "3a19dd55-d443-6b95-2414-e782dd27e3e3",
            SourceSentence = "I click \"Btn_New Quote\"",
            Module = "EQ||New Quote",
            Operation = CanonicalOperation.Click,
            Target = "Btn_New Quote",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0013:0004",
            Sequence = 4,
            SourceStep = "0013",
            SourceName = "Client Selection-Enter Client Info of New or Exisiting Clients",
            SourceXTestStep = "3a19dd55-d49d-6991-8246-f114ce750615",
            SourceSentence = "I wait until \"Lbl_Client Info\" exists",
            Module = "EQ || Client Selection",
            Operation = CanonicalOperation.Wait,
            Target = "Lbl_Client Info",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0013:0005",
            Sequence = 5,
            SourceStep = "0013",
            SourceName = "Client Selection-Enter Client Info of New or Exisiting Clients",
            SourceXTestStep = "3a19dd55-d49d-6991-8246-f114ce750615",
            SourceSentence = "\"Lbl_Client Info\" should equal \"Client Info\"",
            Module = "EQ || Client Selection",
            Operation = CanonicalOperation.Verify,
            Target = "Lbl_Client Info",
            ValueExpression = "",
            ExpectedExpression = "{{data:expected_lbl_client_info_5}}",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0013:0006",
            Sequence = 6,
            SourceStep = "0013",
            SourceName = "Client Selection-Enter Client Info of New or Exisiting Clients",
            SourceXTestStep = "3a19dd55-d49d-6991-8246-f114ce750615",
            SourceSentence = "I enter the RUNTIME-DERIVED TDM value \"AL_ClientData.First Name\" in \"Txt_First\"",
            Module = "EQ || Client Selection",
            Operation = CanonicalOperation.ExternalInput,
            Target = "Txt_First",
            ValueExpression = "{{external:AL_ClientData.First Name}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "AL_ClientData.First Name",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0013:0007",
            Sequence = 7,
            SourceStep = "0013",
            SourceName = "Client Selection-Enter Client Info of New or Exisiting Clients",
            SourceXTestStep = "3a19dd55-d49d-6991-8246-f114ce750615",
            SourceSentence = "I enter the RUNTIME-DERIVED TDM value \"AL_ClientData.Last Name\" in \"Txt_Last\"",
            Module = "EQ || Client Selection",
            Operation = CanonicalOperation.ExternalInput,
            Target = "Txt_Last",
            ValueExpression = "{{external:AL_ClientData.Last Name}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "AL_ClientData.Last Name",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0013:0008",
            Sequence = 8,
            SourceStep = "0013",
            SourceName = "Client Selection-Enter Client Info of New or Exisiting Clients",
            SourceXTestStep = "3a19dd55-d49d-6991-8246-f114ce750615",
            SourceSentence = "I wait until \"Btn_Search\" exists",
            Module = "EQ || Client Selection",
            Operation = CanonicalOperation.Wait,
            Target = "Btn_Search",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0013:0009",
            Sequence = 9,
            SourceStep = "0013",
            SourceName = "Client Selection-Enter Client Info of New or Exisiting Clients",
            SourceXTestStep = "3a19dd55-d49d-6991-8246-f114ce750615",
            SourceSentence = "I click \"Btn_Search\"",
            Module = "EQ || Client Selection",
            Operation = CanonicalOperation.Click,
            Target = "Btn_Search",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0013:0010",
            Sequence = 10,
            SourceStep = "0013",
            SourceName = "Client Selection-Enter Client Info of New or Exisiting Clients",
            SourceXTestStep = "3a19dd55-d49d-6991-8246-f114ce750615",
            SourceSentence = "I wait until \"Btn_Create New Client\" has \"InnerText\" equal to \"Create New Client\"",
            Module = "EQ || Client Selection",
            Operation = CanonicalOperation.Wait,
            Target = "Btn_Create New Client",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0013:0011",
            Sequence = 11,
            SourceStep = "0013",
            SourceName = "Client Selection-Enter Client Info of New or Exisiting Clients",
            SourceXTestStep = "3a19dd55-d49d-6991-8246-f114ce750615",
            SourceSentence = "I click \"Btn_Create New Client\"",
            Module = "EQ || Client Selection",
            Operation = CanonicalOperation.Click,
            Target = "Btn_Create New Client",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0013:0012",
            Sequence = 12,
            SourceStep = "0013",
            SourceName = "Client Selection-Enter Client Info of New or Exisiting Clients",
            SourceXTestStep = "3a19dd55-d49d-6991-8246-f114ce750615",
            SourceSentence = "I click \"Btn_Next\"",
            Module = "EQ || Client Selection",
            Operation = CanonicalOperation.Click,
            Target = "Btn_Next",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0014:0013",
            Sequence = 13,
            SourceStep = "0014",
            SourceName = "Set StateName",
            SourceXTestStep = "3a1a96b2-e11f-e48e-9f6e-bb78c0d69fc1",
            SourceSentence = "I retain hard-coded value \"ALABAMA\" as runtime value \"StateName\"",
            Module = "TBox Set Buffer",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:statename}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "StateName",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0014:0014",
            Sequence = 14,
            SourceStep = "0014",
            SourceName = "Set StateName",
            SourceXTestStep = "3a1a96b2-e11f-e48e-9f6e-bb78c0d69fc1",
            SourceSentence = "I retain the unresolved source parameter \"State Abbreviation\" (not supplied by this reusable-block invocation) as runtime value \"State\"",
            Module = "TBox Set Buffer",
            Operation = CanonicalOperation.ExternalValue,
            Target = "",
            ValueExpression = "{{external:State Abbreviation}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "State",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "State Abbreviation",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0015",
            Sequence = 15,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I wait until \"Lbl_Account Information\" exists",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Wait,
            Target = "Lbl_Account Information",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0016",
            Sequence = 16,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "\"Txt_First Name_Account Owner\" should exist",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Verify,
            Target = "Txt_First Name_Account Owner",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0017",
            Sequence = 17,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I enter the RUNTIME-DERIVED TDM value \"AL_ClientData.DOB\" in \"Txt_DOB\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.ExternalInput,
            Target = "Txt_DOB",
            ValueExpression = "{{external:AL_ClientData.DOB}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "AL_ClientData.DOB",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0018",
            Sequence = 18,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I enter or select \"5555551234\" in \"Txt_Best phone_Account Owner\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Input,
            Target = "Txt_Best phone_Account Owner",
            ValueExpression = "{{data:txt_best_phone_account_owner_18}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0019",
            Sequence = 19,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I enter or select \"a@a.com\" in \"Txt_Email_Account Owner\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Input,
            Target = "Txt_Email_Account Owner",
            ValueExpression = "{{data:txt_email_account_owner_19}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0020",
            Sequence = 20,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I wait until \"Lbl_Marital Status:\" exists",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Wait,
            Target = "Lbl_Marital Status:",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0021",
            Sequence = 21,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I click \"Btn_Single\" when \"'Marital Status' == \\\"Single\\\"\" is satisfied",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Click,
            Target = "Btn_Single",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "'Marital Status' == \"Single\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0022",
            Sequence = 22,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I select \"Btn_Married\" when \"'Marital Status' == \\\"Married\\\"\" is satisfied",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Select,
            Target = "Btn_Married",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "'Marital Status' == \"Married\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0023",
            Sequence = 23,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I click \"Btn_Divorced\" when \"'Marital Status' == \\\"Divorced\\\"\" is satisfied",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Click,
            Target = "Btn_Divorced",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "'Marital Status' == \"Divorced\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0024",
            Sequence = 24,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I enter the RUNTIME-DERIVED TDM value \"AL_ClientData.Street Address\" in \"Txt_Enter a location\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.ExternalInput,
            Target = "Txt_Enter a location",
            ValueExpression = "{{external:AL_ClientData.Street Address}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "AL_ClientData.Street Address",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0025",
            Sequence = 25,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I enter the unresolved source parameter \"Apartment\" (not supplied by this reusable-block invocation) in \"Txt_owner.address.line2\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.ExternalInput,
            Target = "Txt_owner.address.line2",
            ValueExpression = "{{external:Apartment}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "Apartment",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0026",
            Sequence = 26,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I enter the RUNTIME-DERIVED TDM value \"AL_ClientData.City\" in \"Txt_owner.address.city_New\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.ExternalInput,
            Target = "Txt_owner.address.city_New",
            ValueExpression = "{{external:AL_ClientData.City}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "AL_ClientData.City",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0027",
            Sequence = 27,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I select \"Drpdwn_State\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Select,
            Target = "Drpdwn_State",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0028",
            Sequence = 28,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I select \"State Name\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Select,
            Target = "State Name",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0029",
            Sequence = 29,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I enter the RUNTIME-DERIVED TDM value \"AL_ClientData.ZIP\" in \"Txt_owner.address.zip\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.ExternalInput,
            Target = "Txt_owner.address.zip",
            ValueExpression = "{{external:AL_ClientData.ZIP}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "AL_ClientData.ZIP",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0015:0030",
            Sequence = 30,
            SourceStep = "0015",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a19dd55-d4bb-5344-2b53-6fbb792cb2ce",
            SourceSentence = "I wait until \"Satellite\" is visible",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Wait,
            Target = "Satellite",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0016:0031",
            Sequence = 31,
            SourceStep = "0016",
            SourceName = "Account Details-Move down the screen",
            SourceXTestStep = "3a20ccea-6d87-3233-e1a5-8febbb16c0cb",
            SourceSentence = "I press \"Shift+Tab\" while focused on \"Btn_Next\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Press,
            Target = "Btn_Next",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:SHIFTTAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0017:0032",
            Sequence = 32,
            SourceStep = "0017",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a20cced-453c-5ea2-16e9-ff5272653480",
            SourceSentence = "I select \"Btn_Yes_at least 90 days\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Select,
            Target = "Btn_Yes_at least 90 days",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0017:0033",
            Sequence = 33,
            SourceStep = "0017",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a20cced-453c-5ea2-16e9-ff5272653480",
            SourceSentence = "I wait until \"Lbl_Is the account address also where the client resides?\" exists",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Wait,
            Target = "Lbl_Is the account address also where the client resides?",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0017:0034",
            Sequence = 34,
            SourceStep = "0017",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a20cced-453c-5ea2-16e9-ff5272653480",
            SourceSentence = "I select \"Btn_Yes_ClientResides\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Select,
            Target = "Btn_Yes_ClientResides",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0017:0035",
            Sequence = 35,
            SourceStep = "0017",
            SourceName = "Account Details-Enter new Account Information",
            SourceXTestStep = "3a20cced-453c-5ea2-16e9-ff5272653480",
            SourceSentence = "I click \"Btn_Next\"",
            Module = "EQ||Account Details",
            Operation = CanonicalOperation.Click,
            Target = "Btn_Next",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyList<CanonicalAction> ProposalStart { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0036",
            Sequence = 36,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I click \"Personal Auto\" when \"LOB == \\\"PersonalAuto\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Click,
            Target = "Personal Auto",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB == \"PersonalAuto\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0037",
            Sequence = 37,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I click \"Motorcycle\" when \"LOB == \\\"Cycle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Click,
            Target = "Motorcycle",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB == \"Cycle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0038",
            Sequence = 38,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I click \"Recreational Vehicle\" when \"LOB == \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Click,
            Target = "Recreational Vehicle",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB == \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0039",
            Sequence = 39,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I enter the RUNTIME-DERIVED date from Tosca expression \"{SENDKEYS[{DATE}]}\" in \"EffectiveDate\" when \"LOB != \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Input,
            Target = "EffectiveDate",
            ValueExpression = "{DATE}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB != \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0040",
            Sequence = 40,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I enter or select \"D2102\" in \"AgentCode\" when \"LOB != \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Input,
            Target = "AgentCode",
            ValueExpression = "{{data:agentcode_40}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB != \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0041",
            Sequence = 41,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I press \"Tab\" while focused on \"AgentCode\" when \"LOB != \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Press,
            Target = "AgentCode",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB != \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0042",
            Sequence = 42,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I press \"Tab\" while focused on \"State\" when \"LOB != \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Press,
            Target = "State",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB != \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0043",
            Sequence = 43,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I select \"State\" when \"LOB != \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Select,
            Target = "State",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB != \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0044",
            Sequence = 44,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I enter or select \"ALABAMA\" in \"State\" when \"LOB != \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Input,
            Target = "State",
            ValueExpression = "{{data:state_44}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB != \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0045",
            Sequence = 45,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I press \"Tab\" while focused on \"State\" when \"LOB != \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Press,
            Target = "State",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB != \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0046",
            Sequence = 46,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I press \"Tab\" while focused on \"WritingCompany\" when \"LOB != \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Press,
            Target = "WritingCompany",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB != \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0047",
            Sequence = 47,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I select \"WritingCompany\" when \"LOB != \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Select,
            Target = "WritingCompany",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB != \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0048",
            Sequence = 48,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I enter or select \"American National Property And Casualty Co.\" in \"WritingCompany\" when \"LOB != \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Input,
            Target = "WritingCompany",
            ValueExpression = "{{data:writingcompany_48}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB != \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0049",
            Sequence = 49,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I press \"Tab\" while focused on \"WritingCompany\" when \"LOB != \\\"RecreationalVehicle\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Press,
            Target = "WritingCompany",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "LOB != \"RecreationalVehicle\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0050",
            Sequence = 50,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I wait until \"SameAsMailingAddress\" is enabled",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Wait,
            Target = "SameAsMailingAddress",
            ValueExpression = "",
            ExpectedExpression = "True",
            PropertyName = "Enabled",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0051",
            Sequence = 51,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I click \"SameAsMailingAddress\"",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Click,
            Target = "SameAsMailingAddress",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0052",
            Sequence = 52,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I enter or select \"Albany\" in \"County_ComboBox\" when \"State == \\\"NEW YORK\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Input,
            Target = "County_ComboBox",
            ValueExpression = "{{data:county_combobox_52}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "State == \"NEW YORK\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0053",
            Sequence = 53,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I enter or select \"Adair\" in \"County_ComboBox\" when \"State == \\\"KENTUCKY\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Input,
            Target = "County_ComboBox",
            ValueExpression = "{{data:county_combobox_53}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "State == \"KENTUCKY\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0054",
            Sequence = 54,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I wait until \"County_Yes\" exists when \"State == \\\"NEW YORK\\\" OR State == \\\"KENTUCKY\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Wait,
            Target = "County_Yes",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "State == \"NEW YORK\" OR State == \"KENTUCKY\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0055",
            Sequence = 55,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I select \"County_Yes\" when \"State == \\\"NEW YORK\\\" OR State == \\\"KENTUCKY\\\"\" is satisfied",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Select,
            Target = "County_Yes",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "State == \"NEW YORK\" OR State == \"KENTUCKY\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0056",
            Sequence = 56,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I wait until \"Start Quote\" is enabled",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Wait,
            Target = "Start Quote",
            ValueExpression = "",
            ExpectedExpression = "True",
            PropertyName = "Enabled",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0018:0057",
            Sequence = 57,
            SourceStep = "0018",
            SourceName = "Proposal Details/Start",
            SourceXTestStep = "3a19dd55-d4bb-4e49-24eb-78fee0c5fb2f",
            SourceSentence = "I click \"Start Quote\"",
            Module = "EQ || Proposal Details/Start",
            Operation = CanonicalOperation.Click,
            Target = "Start Quote",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0019:0058",
            Sequence = 58,
            SourceStep = "0019",
            SourceName = "Invalid Address",
            SourceXTestStep = "3a19dd55-d4bb-623e-b686-7ddf56301640",
            SourceSentence = "if the source runtime condition \"If Invalid Address Pops Up > Condition\" is satisfied, \"Lnk_PROCEED\" should exist",
            Module = "EQ||Proposal Start Proceed & SSN",
            Operation = CanonicalOperation.Verify,
            Target = "Lnk_PROCEED",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "If Invalid Address Pops Up > Condition",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0020:0059",
            Sequence = 59,
            SourceStep = "0020",
            SourceName = "Proceed with Address",
            SourceXTestStep = "3a19dd55-d4bb-d933-1f45-01d7c5884c97",
            SourceSentence = "if the source runtime condition \"If Invalid Address Pops Up > Then\" is satisfied, I click \"Lnk_PROCEED\"",
            Module = "EQ||Proposal Start Proceed & SSN",
            Operation = CanonicalOperation.Click,
            Target = "Lnk_PROCEED",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "If Invalid Address Pops Up > Then",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0021:0060",
            Sequence = 60,
            SourceStep = "0021",
            SourceName = "EQ||Proposal Start Proceed & SSN",
            SourceXTestStep = "3a19dd55-d4bb-2346-4ac1-4484f91279c2",
            SourceSentence = "if the source runtime condition \"If SSN Pops Up > Condition\" is satisfied, I wait until \"Txt_SSN\" exists",
            Module = "EQ||Proposal Start Proceed & SSN",
            Operation = CanonicalOperation.Wait,
            Target = "Txt_SSN",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "If SSN Pops Up > Condition",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0021:0061",
            Sequence = 61,
            SourceStep = "0021",
            SourceName = "EQ||Proposal Start Proceed & SSN",
            SourceXTestStep = "3a19dd55-d4bb-2346-4ac1-4484f91279c2",
            SourceSentence = "\"Lnk_SUBMIT\" should exist",
            Module = "EQ||Proposal Start Proceed & SSN",
            Operation = CanonicalOperation.Verify,
            Target = "Lnk_SUBMIT",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0022:0062",
            Sequence = 62,
            SourceStep = "0022",
            SourceName = "EQ||Proposal Start Proceed & SSN",
            SourceXTestStep = "3a19dd55-d4bb-e07a-c912-67b225b906d7",
            SourceSentence = "if the source runtime condition \"If SSN Pops Up > Then\" is satisfied, I enter the RUNTIME-DERIVED TDM value \"AL_ClientData.SSN\" in \"Txt_SSN\"",
            Module = "EQ||Proposal Start Proceed & SSN",
            Operation = CanonicalOperation.ExternalInput,
            Target = "Txt_SSN",
            ValueExpression = "{{external:AL_ClientData.SSN}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "If SSN Pops Up > Then",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "AL_ClientData.SSN",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0022:0063",
            Sequence = 63,
            SourceStep = "0022",
            SourceName = "EQ||Proposal Start Proceed & SSN",
            SourceXTestStep = "3a19dd55-d4bb-e07a-c912-67b225b906d7",
            SourceSentence = "I click \"Lnk_SUBMIT\"",
            Module = "EQ||Proposal Start Proceed & SSN",
            Operation = CanonicalOperation.Click,
            Target = "Lnk_SUBMIT",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0023:0064",
            Sequence = 64,
            SourceStep = "0023",
            SourceName = "Confirm SSN?",
            SourceXTestStep = "3a19dd55-d4bb-ade4-c507-54a1e1752cd1",
            SourceSentence = "if the source runtime condition \"If SSN Pops Up > Else > If > Condition\" is satisfied, \"Lnk_CONFIRM\" should exist",
            Module = "EQ||Proposal Start Proceed & SSN",
            Operation = CanonicalOperation.Verify,
            Target = "Lnk_CONFIRM",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "If SSN Pops Up > Else > If > Condition",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0024:0065",
            Sequence = 65,
            SourceStep = "0024",
            SourceName = "Select Confirm",
            SourceXTestStep = "3a19dd55-d4bb-3de6-f2d5-e7180cc12529",
            SourceSentence = "if the source runtime condition \"If SSN Pops Up > Else > If > Then\" is satisfied, I click \"Lnk_CONFIRM\"",
            Module = "EQ||Proposal Start Proceed & SSN",
            Operation = CanonicalOperation.Click,
            Target = "Lnk_CONFIRM",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "If SSN Pops Up > Else > If > Then",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0025:0066",
            Sequence = 66,
            SourceStep = "0025",
            SourceName = "Existing Client",
            SourceXTestStep = "3a19dd55-d4bb-9d1a-2059-569b4cf4abc0",
            SourceSentence = "if the source runtime condition \"If Existing Client Pops Up > Condition\" is satisfied, I wait until \"Lnk_USE EXISTING ACCOUNT\" exists",
            Module = "EQ||Proposal Start Proceed & SSN",
            Operation = CanonicalOperation.Wait,
            Target = "Lnk_USE EXISTING ACCOUNT",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "If Existing Client Pops Up > Condition",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0026:0067",
            Sequence = 67,
            SourceStep = "0026",
            SourceName = "Select Existing Client",
            SourceXTestStep = "3a19dd55-d4bb-62d6-6343-5954b89fe8eb",
            SourceSentence = "if the source runtime condition \"If Existing Client Pops Up > Then\" is satisfied, I click \"Lnk_CREATE NEW ACCOUNT\" when \"State == \\\"MONTANA\\\"\" is satisfied",
            Module = "EQ||Proposal Start Proceed & SSN",
            Operation = CanonicalOperation.Click,
            Target = "State == \"MONTANA",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "If Existing Client Pops Up > Then",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0026:0068",
            Sequence = 68,
            SourceStep = "0026",
            SourceName = "Select Existing Client",
            SourceXTestStep = "3a19dd55-d4bb-62d6-6343-5954b89fe8eb",
            SourceSentence = "I click \"Lnk_USE EXISTING ACCOUNT\" when \"State != \\\"MONTANA\\\"\" is satisfied",
            Module = "EQ||Proposal Start Proceed & SSN",
            Operation = CanonicalOperation.Click,
            Target = "Lnk_USE EXISTING ACCOUNT",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "State != \"MONTANA\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0027:0069",
            Sequence = 69,
            SourceStep = "0027",
            SourceName = "TBox Set Effective Date Buffer",
            SourceXTestStep = "3a1a4eb2-e67c-37e2-de7d-16fe80bc5ef8",
            SourceSentence = "I retain the unresolved source parameter \"Effective Date\" (not supplied by this reusable-block invocation) as runtime value \"EffectiveDate\"",
            Module = "TBox Set Buffer",
            Operation = CanonicalOperation.ExternalValue,
            Target = "",
            ValueExpression = "{{external:Effective Date}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "EffectiveDate",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "Effective Date",
            Notes = ""
        },
    };

    public static IReadOnlyList<CanonicalAction> Verification { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0028:0070",
            Sequence = 70,
            SourceStep = "0028",
            SourceName = "EQ||Tabs - Capturing Quote number",
            SourceXTestStep = "3a19dd55-d443-9c9d-9370-343c6da34248",
            SourceSentence = "I capture \"Text\" from \"Lbl_QNum\" as runtime value \"QuoteNumber2\"",
            Module = "EQ||Tabs",
            Operation = CanonicalOperation.Capture,
            Target = "Lbl_QNum",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "Text",
            Alias = "QuoteNumber2",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0029:0071",
            Sequence = 71,
            SourceStep = "0029",
            SourceName = "TBox Set Buffer - Trimming Quote number",
            SourceXTestStep = "3a19dd55-d443-fb9d-e604-b32de4887229",
            SourceSentence = "I derive and retain the RUNTIME-DERIVED buffer expression \"{STRINGREPLACE[{B[QuoteNumber2]}][\\\"PERSONAL AUTO \\\"][\\\"\\\"]}\" as runtime value \"QuoteNumber3\"",
            Module = "TBox Set Buffer",
            Operation = CanonicalOperation.Evaluate,
            Target = "",
            ValueExpression = "{STRINGREPLACE[{B[QuoteNumber2]}][\"PERSONAL AUTO \"][\"\"]}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "QuoteNumber3",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0029:0072",
            Sequence = 72,
            SourceStep = "0029",
            SourceName = "TBox Set Buffer - Trimming Quote number",
            SourceXTestStep = "3a19dd55-d443-fb9d-e604-b32de4887229",
            SourceSentence = "I derive and retain the RUNTIME-DERIVED buffer expression \"{STRINGREPLACE[{B[QuoteNumber3]}][\\\"\\\\(\\\"][\\\"\\\"]}\" as runtime value \"QuoteNumber4\"",
            Module = "TBox Set Buffer",
            Operation = CanonicalOperation.Evaluate,
            Target = "",
            ValueExpression = "{STRINGREPLACE[{B[QuoteNumber3]}][\"\\(\"][\"\"]}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "QuoteNumber4",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0029:0073",
            Sequence = 73,
            SourceStep = "0029",
            SourceName = "TBox Set Buffer - Trimming Quote number",
            SourceXTestStep = "3a19dd55-d443-fb9d-e604-b32de4887229",
            SourceSentence = "I derive and retain the RUNTIME-DERIVED buffer expression \"{STRINGREPLACE[{B[QuoteNumber4]}][\\\"\\\\)\\\"][\\\"\\\"]}\" as runtime value \"QuoteNumber\"",
            Module = "TBox Set Buffer",
            Operation = CanonicalOperation.Evaluate,
            Target = "",
            ValueExpression = "{STRINGREPLACE[{B[QuoteNumber4]}][\"\\)\"][\"\"]}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "QuoteNumber",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0030:0074",
            Sequence = 74,
            SourceStep = "0030",
            SourceName = "EQ||Tabs",
            SourceXTestStep = "3a19e1e5-1883-1142-ce28-23ecc0a20ea3",
            SourceSentence = "I click \"Btn_Close_tab\"",
            Module = "EQ||Tabs",
            Operation = CanonicalOperation.Click,
            Target = "Btn_Close_tab",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0030:0075",
            Sequence = 75,
            SourceStep = "0030",
            SourceName = "EQ||Tabs",
            SourceXTestStep = "3a19e1e5-1883-1142-ce28-23ecc0a20ea3",
            SourceSentence = "I enter captured runtime value \"QuoteNumber\" in \"Txt_quoteSearchInput\"",
            Module = "EQ||Tabs",
            Operation = CanonicalOperation.Input,
            Target = "Txt_quoteSearchInput",
            ValueExpression = "{{runtime:QuoteNumber}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0030:0076",
            Sequence = 76,
            SourceStep = "0030",
            SourceName = "EQ||Tabs",
            SourceXTestStep = "3a19e1e5-1883-1142-ce28-23ecc0a20ea3",
            SourceSentence = "I click \"Btn_Search\"",
            Module = "EQ||Tabs",
            Operation = CanonicalOperation.Click,
            Target = "Btn_Search",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0031:0077",
            Sequence = 77,
            SourceStep = "0031",
            SourceName = "EQ||Tabs",
            SourceXTestStep = "3a19e1e5-1886-9249-c81c-7ab03ed3aa8f",
            SourceSentence = "I capture \"Text\" from \"Lbl_QNum\" as runtime value \"QuoteNumber6\"",
            Module = "EQ||Tabs",
            Operation = CanonicalOperation.Capture,
            Target = "Lbl_QNum",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "Text",
            Alias = "QuoteNumber6",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0031:0078",
            Sequence = 78,
            SourceStep = "0031",
            SourceName = "EQ||Tabs",
            SourceXTestStep = "3a19e1e5-1886-9249-c81c-7ab03ed3aa8f",
            SourceSentence = "\"Lbl_QNum\" should equal captured runtime value \"QuoteNumber2\"",
            Module = "EQ||Tabs",
            Operation = CanonicalOperation.Verify,
            Target = "Lbl_QNum",
            ValueExpression = "",
            ExpectedExpression = "{{runtime:QuoteNumber2}}",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0032:0079",
            Sequence = 79,
            SourceStep = "0032",
            SourceName = "TBox Set Buffer",
            SourceXTestStep = "3a19e1e5-1886-041e-72d2-8f90d7c47f54",
            SourceSentence = "I derive and retain the RUNTIME-DERIVED buffer expression \"{STRINGREPLACE[{B[QuoteNumber6]}][\\\"PERSONAL AUTO \\\"][\\\"\\\"]}\" as runtime value \"QuoteNumber7\"",
            Module = "TBox Set Buffer",
            Operation = CanonicalOperation.Evaluate,
            Target = "",
            ValueExpression = "{STRINGREPLACE[{B[QuoteNumber6]}][\"PERSONAL AUTO \"][\"\"]}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "QuoteNumber7",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0032:0080",
            Sequence = 80,
            SourceStep = "0032",
            SourceName = "TBox Set Buffer",
            SourceXTestStep = "3a19e1e5-1886-041e-72d2-8f90d7c47f54",
            SourceSentence = "I derive and retain the RUNTIME-DERIVED buffer expression \"{STRINGREPLACE[{B[QuoteNumber7]}][\\\"\\\\(\\\"][\\\"\\\"]}\" as runtime value \"QuoteNumber8\"",
            Module = "TBox Set Buffer",
            Operation = CanonicalOperation.Evaluate,
            Target = "",
            ValueExpression = "{STRINGREPLACE[{B[QuoteNumber7]}][\"\\(\"][\"\"]}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "QuoteNumber8",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "Smoke_Test_Auto:0032:0081",
            Sequence = 81,
            SourceStep = "0032",
            SourceName = "TBox Set Buffer",
            SourceXTestStep = "3a19e1e5-1886-041e-72d2-8f90d7c47f54",
            SourceSentence = "I derive and retain the RUNTIME-DERIVED buffer expression \"{STRINGREPLACE[{B[QuoteNumber8]}][\\\"\\\\)\\\"][\\\"\\\"]}\" as runtime value \"QuoteNumber9\"",
            Module = "TBox Set Buffer",
            Operation = CanonicalOperation.Evaluate,
            Target = "",
            ValueExpression = "{STRINGREPLACE[{B[QuoteNumber8]}][\"\\)\"][\"\"]}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "QuoteNumber9",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyDictionary<string, IReadOnlyList<CanonicalAction>> AllStages { get; } =
        new Dictionary<string, IReadOnlyList<CanonicalAction>>(StringComparer.OrdinalIgnoreCase)
        {
            ["ClientAndAccount"] = ClientAndAccount,
            ["ProposalStart"] = ProposalStart,
            ["Verification"] = Verification,
        };
}
