<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ReqnrollUseIntermediateOutputPathForCodeBehind>true</ReqnrollUseIntermediateOutputPathForCodeBehind>
      <RunSettingsFilePath>$(MSBuildThisFileDirectory)Tosca.runsettings</RunSettingsFilePath>
  </PropertyGroup>
</Project>
