<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ReqnrollUseIntermediateOutputPathForCodeBehind>true</ReqnrollUseIntermediateOutputPathForCodeBehind>
      <RunSettingsFilePath>$(MSBuildThisFileDirectory)Tosca.runsettings</RunSettingsFilePath>
  </PropertyGroup>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)reqnroll.json" Link="reqnroll.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup Condition="$([System.String]::Copy('$(MSBuildProjectName)').EndsWith('.Tests'))">
    <Compile Include="$(MSBuildThisFileDirectory)Parallelization.cs" Link="Parallelization.cs" />
  </ItemGroup>
</Project>
