// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace InsuranceAutomation.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("EQ BOP Basic Policy")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("bop-eq")]
    [global::NUnit.Framework.CategoryAttribute("generated")]
    [global::NUnit.Framework.CategoryAttribute("eq-bop-basic-policy")]
    public partial class EQBOPBasicPolicyFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "bop-eq",
                "generated",
                "eq-bop-basic-policy"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "EQ BOP Basic Policy", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "eq-bop-basic-policy.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/eq-bop-basic-policy.feature.ndjson", 47);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("EQ BOP Basic Policy - <stateCode>")]
        [global::NUnit.Framework.TestCaseAttribute("TestData/al.json", "AL", "Alabama", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ar.json", "AR", "Arkansas", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/az.json", "AZ", "Arizona", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ca.json", "CA", "California", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/co.json", "CO", "Colorado", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ct.json", "CT", "Connecticut", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/de.json", "DE", "Delaware", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ga.json", "GA", "Georgia", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ia.json", "IA", "Iowa", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/id.json", "ID", "Idaho", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/il.json", "IL", "Illinois", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/in.json", "IN", "Indiana", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ks.json", "KS", "Kansas", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ky.json", "KY", "Kentucky", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/la.json", "LA", "Louisiana", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ma.json", "MA", "Massachusetts", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/md.json", "MD", "Maryland", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/me.json", "ME", "Maine", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/mn.json", "MN", "Minnesota", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/mo.json", "MO", "Missouri", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ms.json", "MS", "Mississippi", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/mt.json", "MT", "Montana", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/nd.json", "ND", "North Dakota", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ne.json", "NE", "Nebraska", "23", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/nh.json", "NH", "New Hampshire", "24", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/nj.json", "NJ", "New Jersey", "25", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/nm.json", "NM", "New Mexico", "26", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/nv.json", "NV", "Nevada", "27", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ny.json", "NY", "New York", "28", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/oh.json", "OH", "Ohio", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ok.json", "OK", "Oklahoma", "30", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/or.json", "OR", "Oregon", "31", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/pa.json", "PA", "Pennsylvania", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ri.json", "RI", "Rhode Island", "33", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/sc.json", "SC", "South Carolina", "34", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/sd.json", "SD", "South Dakota", "35", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/tn.json", "TN", "Tennessee", "36", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/tx.json", "TX", "Texas", "37", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/ut.json", "UT", "Utah", "38", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/va.json", "VA", "Virginia", "39", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/vt.json", "VT", "Vermont", "40", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/wa.json", "WA", "Washington", "41", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/wi.json", "WI", "Wisconsin", "42", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/wv.json", "WV", "West Virginia", "43", null)]
        [global::NUnit.Framework.TestCaseAttribute("TestData/wy.json", "WY", "Wyoming", "44", null)]
        public async global::System.Threading.Tasks.Task EQBOPBasicPolicy_StateCode(string dataFile, string stateCode, string stateName, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("dataFile", dataFile);
            argumentsOfScenario.Add("stateCode", stateCode);
            argumentsOfScenario.Add("stateName", stateName);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("EQ BOP Basic Policy - <stateCode>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync(string.Format("test data file \"{0}\" is loaded", dataFile), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync(string.Format("the policy jurisdiction is \"{0}\"", stateCode), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync(string.Format("the policy state is \"{0}\"", stateName), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.AndAsync("I open EQ in the browser", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.AndAsync("I sign in to EQ", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.AndAsync("I start a new quote", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.WhenAsync("I enter client search information", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
    await testRunner.AndAsync("I create a new client", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.AndAsync("I enter account information", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.AndAsync("I complete the proposal start", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.AndAsync("I enter the insured social security number", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync("I navigate to the prequalification screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.AndAsync("I search for and add the required business class", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.AndAsync("I confirm the general eligibility restrictions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
    await testRunner.AndAsync("I complete the industry class-code restrictions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.AndAsync("I navigate to the primary insured details screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
    await testRunner.AndAsync("I enter the required primary-insured information", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.AndAsync("I answer the primary-insured underwriting questions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
    await testRunner.AndAsync("I answer the industry class-code questions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync("I navigate to the client details screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync("I assign the required client roles", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
    await testRunner.AndAsync("I navigate to the narrative screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.AndAsync("I add the underwriting narrative and verify its timestamp", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.AndAsync("I enter the prior-claims information", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync("I maintain and verify prior claims", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.AndAsync("I navigate to locations and buildings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
    await testRunner.AndAsync("I enter the policy location", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
    await testRunner.AndAsync("I navigate to the add building screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
    await testRunner.AndAsync("I add a building", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
    await testRunner.AndAsync("I enter building ownership and square footage", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
    await testRunner.AndAsync("I select the required building coverages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
    await testRunner.AndAsync("I enter occupancy square footage", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
    await testRunner.AndAsync("I enter class-specific supplemental building data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
    await testRunner.AndAsync("I calculate the building valuation", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
    await testRunner.AndAsync("I enter the building details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
    await testRunner.AndAsync("I enter the building heating sources", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
    await testRunner.AndAsync("I select the additional property-risk options", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
    await testRunner.AndAsync("I answer the building eligibility questions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 50
    await testRunner.AndAsync("I review the required-information message", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.AndAsync("I navigate to policy coverages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
    await testRunner.AndAsync("I navigate to additional coverages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 53
    await testRunner.AndAsync("I remove EPLI coverage when it is not applicable", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
    await testRunner.AndAsync("I answer the EPLI coverage questions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
    await testRunner.AndAsync("I answer the designated-work exclusion question", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
    await testRunner.AndAsync("I enter liquor-liability gross sales and event details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.AndAsync("I select the liquor-liability activity description", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
    await testRunner.AndAsync("I confirm no additional liquor-liability conditions apply", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
    await testRunner.AndAsync("I navigate to billing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
    await testRunner.AndAsync("I configure the billing account", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
    await testRunner.AndAsync("I select the future payment plan", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
    await testRunner.AndAsync("I enter the initial payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 63
    await testRunner.AndAsync("I navigate to pricing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
    await testRunner.AndAsync("I return to billing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
    await testRunner.AndAsync("I return to pricing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 66
    await testRunner.AndAsync("I calculate and verify the premium", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 67
    await testRunner.AndAsync("I verify the applicable risk category", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 68
    await testRunner.AndAsync("I navigate to the submission screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 69
    await testRunner.AndAsync("I verify the policy jacket", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.AndAsync("I return to the quote in EQ", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 71
    await testRunner.AndAsync("I verify the generated forms", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
    await testRunner.AndAsync("I return to the quote in EQ", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
    await testRunner.AndAsync("I return to the submission screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
    await testRunner.AndAsync("I complete the submission checklist and electronic signature", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
    await testRunner.AndAsync("I complete the policy checklist", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
    await testRunner.AndAsync("I refer the quote to underwriting", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.AndAsync("I approve the referral as an underwriter", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
    await testRunner.AndAsync("I return to the active quote in EQ", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
    await testRunner.AndAsync("I return to the primary insured details screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
    await testRunner.AndAsync("I transmit the policy", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 81
    await testRunner.AndAsync("I verify the new-business policy packet", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 82
    await testRunner.AndAsync("I verify the premium in the policy administration system", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
    await testRunner.AndAsync("I complete the regression verification", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
    await testRunner.ThenAsync("I sign out of the underwriting application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 87
    await testRunner.AndAsync("I complete the business postcondition", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
