using ToscaArtifactAutomation.Core.Canonical;

namespace ToscaArtifactAutomation.CLEQ.CanonicalMaps;

public static class EQBOPSmokeTestCanonicalMap
{
    public static IReadOnlyList<CanonicalAction> ClientAndAccount { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0001",
            Sequence = 1,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "the \"New Quote\" control is visible",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "New Quote",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0002",
            Sequence = 2,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "I click \"New Quote\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "New Quote",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0003",
            Sequence = 3,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "I generate and retain a RANDOM first name matching \"BOP [a-z]{3}\" as \"FirstName\"",
            Module = "",
            Operation = CanonicalOperation.GenerateRandom,
            Target = "",
            ValueExpression = "BOP [a-z]{3}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "FirstName",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0004",
            Sequence = 4,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "I generate and retain a RANDOM last name matching \"Smoke[a-z]{4}\" as \"LastName\"",
            Module = "",
            Operation = CanonicalOperation.GenerateRandom,
            Target = "",
            ValueExpression = "Smoke[a-z]{4}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "LastName",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0005",
            Sequence = 5,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "the \"Client Info\" and \"New/Existing Client Search\" sections should be visible",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "Client Info",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0006",
            Sequence = 6,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "I enter the retained RANDOM value \"FirstName\" in the client first-name field",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "customer.name.first",
            ValueExpression = "{{runtime:FirstName}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0007",
            Sequence = 7,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "I enter the retained RANDOM value \"LastName\" in the client last-name field",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "customer.name.last",
            ValueExpression = "{{runtime:LastName}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0008",
            Sequence = 8,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "I enter date of birth \"08/13/2004\"",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "customer.dateOfBirth",
            ValueExpression = "{{data:customer_dateofbirth}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0009",
            Sequence = 9,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "I click \"Search\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Search",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0010",
            Sequence = 10,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "the \"Existing Client Match\" section should be displayed",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "Existing Client Match",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0011",
            Sequence = 11,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "I click \"Create New Client\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Create New Client",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0028-0031:0012",
            Sequence = 12,
            SourceStep = "0028-0031",
            SourceName = "begin quote and create a new client.",
            SourceXTestStep = "",
            SourceSentence = "I click \"Next\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Next",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038:0013",
            Sequence = 13,
            SourceStep = "0032-0038",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "the \"Account Information\" header should be visible",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "Account Information",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038:0014",
            Sequence = 14,
            SourceStep = "0032-0038",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I leave \"Owner Middle Name\" blank",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "Owner Middle Name",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038:0015",
            Sequence = 15,
            SourceStep = "0032-0038",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I enter a RANDOM 10-digit owner phone number matching \"3[0-9]{9}\"",
            Module = "",
            Operation = CanonicalOperation.GenerateRandom,
            Target = "Owner Phone",
            ValueExpression = "3[0-9]{9}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "OwnerPhone",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038:0016",
            Sequence = 16,
            SourceStep = "0032-0038",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I enter a RANDOM owner email address matching \"test@[a-z]{4}.com\"",
            Module = "",
            Operation = CanonicalOperation.GenerateRandom,
            Target = "Owner Email",
            ValueExpression = "test@[a-z]{4}.com",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "OwnerEmail",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038:0017",
            Sequence = 17,
            SourceStep = "0032-0038",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I select marital status \"Married\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Married",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038.row01:0018",
            Sequence = 18,
            SourceStep = "0032-0038.row01",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I enter \"317 Park Central East\" in \"Street Address\"",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "Street Address",
            ValueExpression = "{{data:street_address_18}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038.row02:0019",
            Sequence = 19,
            SourceStep = "0032-0038.row02",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I leave \"Address 2\" blank",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "Address 2",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038.row03:0020",
            Sequence = 20,
            SourceStep = "0032-0038.row03",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I enter \"Springfield\" in \"City\"",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "City",
            ValueExpression = "{{data:city_20}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038.row04:0021",
            Sequence = 21,
            SourceStep = "0032-0038.row04",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I enter \"Missouri\" in \"State\"",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "State",
            ValueExpression = "{{data:state_21}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038.row05:0022",
            Sequence = 22,
            SourceStep = "0032-0038.row05",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I enter \"65805\" in \"ZIP\"",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "ZIP",
            ValueExpression = "{{data:zip_22}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038:0023",
            Sequence = 23,
            SourceStep = "0032-0038",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "the \"Map\" control should exist",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "Map",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038:0024",
            Sequence = 24,
            SourceStep = "0032-0038",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "the \"Satellite\" control should exist",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "Satellite",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038:0025",
            Sequence = 25,
            SourceStep = "0032-0038",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I answer \"Yes\" to \"Have you received mail at this address for at least 90 days?\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Have you received mail at this address for at least 90 days? > Yes",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038:0026",
            Sequence = 26,
            SourceStep = "0032-0038",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I answer \"Yes\" to \"Is the account address also where the client resides?\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Is the account address also where the client resides? > Yes",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0032-0038:0027",
            Sequence = 27,
            SourceStep = "0032-0038",
            SourceName = "account information and address.",
            SourceXTestStep = "",
            SourceSentence = "I click \"Next\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Next",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyList<CanonicalAction> ProposalStart { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0028",
            Sequence = 28,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "the \"Proposal Details\" header should be visible",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "Proposal Details",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0029",
            Sequence = 29,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "I select line of business \"Business Owners\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Business Owners",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0030",
            Sequence = 30,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "I move past the \"Search Business Name\" field without entering a business name",
            Module = "",
            Operation = CanonicalOperation.Press,
            Target = "Search Business Name",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:ENTER" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0031",
            Sequence = 31,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "for this one manual iteration I use business type \"Individual\"",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "Individual",
            ValueExpression = "{{data:individual_31}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0032",
            Sequence = 32,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "I select business ownership \"Individually Owned, DBA, or T/A\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Individually Owned, DBA, or T/A",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0033",
            Sequence = 33,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "I enter individual DBA name \"Tester Automation\"",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "Individual DBA",
            ValueExpression = "{{data:individual_dba}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0034",
            Sequence = 34,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "I enter effective date \"03-01-2025\"",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "Effective Date",
            ValueExpression = "{{data:effective_date}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0035",
            Sequence = 35,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "I keep the new-account-address indicator set to \"True\"",
            Module = "",
            Operation = CanonicalOperation.SmartSet,
            Target = "newAccountAddress",
            ValueExpression = "{{data:new_account_address}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0036",
            Sequence = 36,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "I answer \"No\" to \"Lessors Risk\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Lessors Risk > No",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0037",
            Sequence = 37,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "I select state \"Missouri\"",
            Module = "",
            Operation = CanonicalOperation.Select,
            Target = "Missouri",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0038",
            Sequence = 38,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "I enter agent producer code \"D2102\"",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "AgentPC",
            ValueExpression = "{{data:agentpc}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0039",
            Sequence = 39,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "I retain the displayed effective date as runtime value \"EffDate\"",
            Module = "",
            Operation = CanonicalOperation.Capture,
            Target = "Effective Date",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "Value",
            Alias = "EffDate",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0040",
            Sequence = 40,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "I click \"Start Quote\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Start Quote",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0039-0040:0041",
            Sequence = 41,
            SourceStep = "0039-0040",
            SourceName = "proposal creation data.",
            SourceXTestStep = "",
            SourceSentence = "the runtime line-of-business value should be retained as \"BOP\"",
            Module = "",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:line_of_business}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "LOB",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyList<CanonicalAction> IdentityAndPrefill { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0041-0044:0042",
            Sequence = 42,
            SourceStep = "0041-0044",
            SourceName = "SSN entry and optional no-prefill-match handling.",
            SourceXTestStep = "",
            SourceSentence = "the technical wait buffer is set to \"5000\" milliseconds",
            Module = "",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:wait_on_time}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "WaitOnTime",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0041-0044:0043",
            Sequence = 43,
            SourceStep = "0041-0044",
            SourceName = "SSN entry and optional no-prefill-match handling.",
            SourceXTestStep = "",
            SourceSentence = "the message \"The SSN could not be found. Please enter an SSN.\" should be visible",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "The SSN could not be found. Please enter an SSN.",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0041-0044:0044",
            Sequence = 44,
            SourceStep = "0041-0044",
            SourceName = "SSN entry and optional no-prefill-match handling.",
            SourceXTestStep = "",
            SourceSentence = "I enter a RANDOM 9-digit SSN consisting of fixed prefix \"025\" followed by \"6\" random digits",
            Module = "",
            Operation = CanonicalOperation.GenerateRandom,
            Target = "ssn",
            ValueExpression = "025[0-9]{6}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "InsuredSSN",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0041-0044:0045",
            Sequence = 45,
            SourceStep = "0041-0044",
            SourceName = "SSN entry and optional no-prefill-match handling.",
            SourceXTestStep = "",
            SourceSentence = "I move focus away from the SSN field",
            Module = "",
            Operation = CanonicalOperation.Press,
            Target = "",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0041-0044:0046",
            Sequence = 46,
            SourceStep = "0041-0044",
            SourceName = "SSN entry and optional no-prefill-match handling.",
            SourceXTestStep = "",
            SourceSentence = "the active Angular \"Submit\" control should be visible",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "Submit",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0041-0044:0047",
            Sequence = 47,
            SourceStep = "0041-0044",
            SourceName = "SSN entry and optional no-prefill-match handling.",
            SourceXTestStep = "",
            SourceSentence = "I activate the active Angular \"Submit\" control",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Submit",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0041-0044:0048",
            Sequence = 48,
            SourceStep = "0041-0044",
            SourceName = "SSN entry and optional no-prefill-match handling.",
            SourceXTestStep = "",
            SourceSentence = "if the \"No Prefill Match Found\" popup is displayed, I click \"Continue\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Continue",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "if the \"No Prefill Match Found\" popup is displayed",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyList<CanonicalAction> PreQualification { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0045-0053:0049",
            Sequence = 49,
            SourceStep = "0045-0053",
            SourceName = "navigate to the target screen.",
            SourceXTestStep = "",
            SourceSentence = "the technical wait buffer is set to \"25000\" milliseconds",
            Module = "",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:wait_on_time_2}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "WaitOnTime",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0045-0053:0050",
            Sequence = 50,
            SourceStep = "0045-0053",
            SourceName = "navigate to the target screen.",
            SourceXTestStep = "",
            SourceSentence = "the required target screen is \"PreQualification\"",
            Module = "",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:required_target_screen}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "Screen",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0045-0053:0051",
            Sequence = 51,
            SourceStep = "0045-0053",
            SourceName = "navigate to the target screen.",
            SourceXTestStep = "",
            SourceSentence = "the current screen is not \"PreQualification\", I use the navigation link for \"PreQualification\"",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "PreQualification",
            ValueExpression = "{{data:prequalification_51}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0045-0053:0052",
            Sequence = 52,
            SourceStep = "0045-0053",
            SourceName = "navigate to the target screen.",
            SourceXTestStep = "",
            SourceSentence = "if the \"Review Required\" popup is displayed and the configured action is \"Keep Going\", I click \"Keep Going\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Keep Going",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "if the \"Review Required\" popup is displayed and the configured action is \"Keep Going\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0045-0053:0053",
            Sequence = 53,
            SourceStep = "0045-0053",
            SourceName = "navigate to the target screen.",
            SourceXTestStep = "",
            SourceSentence = "I wait until the configured ExpertQuote loading-indicator condition is satisfied",
            Module = "",
            Operation = CanonicalOperation.Wait,
            Target = "Loading ...",
            ValueExpression = "",
            ExpectedExpression = "Absent",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 60000,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = "ExpertQuote loading-indicator wait compiled to an observable absent condition."
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0045-0053:0054",
            Sequence = 54,
            SourceStep = "0045-0053",
            SourceName = "navigate to the target screen.",
            SourceXTestStep = "",
            SourceSentence = "the \"PreQualification\" screen heading should exist",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "PreQualification",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyList<CanonicalAction> Verification { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0054-0056:0055",
            Sequence = 55,
            SourceStep = "0054-0056",
            SourceName = "capture the quote identity and close the quote.",
            SourceXTestStep = "",
            SourceSentence = "I capture the full displayed \"Name and Quote\" text as runtime value \"Quote_NameNum\"",
            Module = "",
            Operation = CanonicalOperation.Capture,
            Target = "Name and Quote",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "InnerText",
            Alias = "Quote_NameNum",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0054-0056:0056",
            Sequence = 56,
            SourceStep = "0054-0056",
            SourceName = "capture the quote identity and close the quote.",
            SourceXTestStep = "",
            SourceSentence = "I derive runtime value \"Quote_Num\" by removing the retained RANDOM \"LastName\" from \"Quote_NameNum\"",
            Module = "",
            Operation = CanonicalOperation.Evaluate,
            Target = "",
            ValueExpression = "{{runtime:Quote_NameNum}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "Quote_Num",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "REMOVE_RUNTIME:LastName" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0054-0056:0057",
            Sequence = 57,
            SourceStep = "0054-0056",
            SourceName = "capture the quote identity and close the quote.",
            SourceXTestStep = "",
            SourceSentence = "I retain \"Quote_Num\" as runtime value \"QuoteID\"",
            Module = "",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{runtime:QuoteID}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "Quote_Num",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0054-0056:0058",
            Sequence = 58,
            SourceStep = "0054-0056",
            SourceName = "capture the quote identity and close the quote.",
            SourceXTestStep = "",
            SourceSentence = "I click \"Close Quote\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Close Quote",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0057-0068:0059",
            Sequence = 59,
            SourceStep = "0057-0068",
            SourceName = "search for the same quote and verify identity.",
            SourceXTestStep = "",
            SourceSentence = "I wait until the configured ExpertQuote loading-indicator condition is satisfied",
            Module = "",
            Operation = CanonicalOperation.Wait,
            Target = "Loading ...",
            ValueExpression = "",
            ExpectedExpression = "Absent",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 60000,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = "ExpertQuote loading-indicator wait compiled to an observable absent condition."
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0057-0068:0060",
            Sequence = 60,
            SourceStep = "0057-0068",
            SourceName = "search for the same quote and verify identity.",
            SourceXTestStep = "",
            SourceSentence = "I enter the captured runtime value \"Quote_Num\" in the quote-search field",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "Quote Search",
            ValueExpression = "{{runtime:Quote_Num}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0057-0068:0061",
            Sequence = 61,
            SourceStep = "0057-0068",
            SourceName = "search for the same quote and verify identity.",
            SourceXTestStep = "",
            SourceSentence = "I click \"Search\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Search",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0057-0068:0062",
            Sequence = 62,
            SourceStep = "0057-0068",
            SourceName = "search for the same quote and verify identity.",
            SourceXTestStep = "",
            SourceSentence = "I wait until the configured ExpertQuote loading-indicator condition is satisfied",
            Module = "",
            Operation = CanonicalOperation.Wait,
            Target = "Loading ...",
            ValueExpression = "",
            ExpectedExpression = "Absent",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 60000,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = "ExpertQuote loading-indicator wait compiled to an observable absent condition."
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0057-0068:0063",
            Sequence = 63,
            SourceStep = "0057-0068",
            SourceName = "search for the same quote and verify identity.",
            SourceXTestStep = "",
            SourceSentence = "the required target screen is \"PreQualification\"",
            Module = "",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:required_target_screen}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "Screen",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0057-0068:0064",
            Sequence = 64,
            SourceStep = "0057-0068",
            SourceName = "search for the same quote and verify identity.",
            SourceXTestStep = "",
            SourceSentence = "the retrieved quote is not on \"PreQualification\", I use the navigation link for \"PreQualification\"",
            Module = "",
            Operation = CanonicalOperation.Input,
            Target = "PreQualification",
            ValueExpression = "{{data:prequalification_64}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0057-0068:0065",
            Sequence = 65,
            SourceStep = "0057-0068",
            SourceName = "search for the same quote and verify identity.",
            SourceXTestStep = "",
            SourceSentence = "if the \"Review Required\" popup is displayed and the configured action is \"Keep Going\", I click \"Keep Going\"",
            Module = "",
            Operation = CanonicalOperation.Click,
            Target = "Keep Going",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "if the \"Review Required\" popup is displayed and the configured action is \"Keep Going\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0057-0068:0066",
            Sequence = 66,
            SourceStep = "0057-0068",
            SourceName = "search for the same quote and verify identity.",
            SourceXTestStep = "",
            SourceSentence = "I wait until the configured ExpertQuote loading-indicator condition is satisfied",
            Module = "",
            Operation = CanonicalOperation.Wait,
            Target = "Loading ...",
            ValueExpression = "",
            ExpectedExpression = "Absent",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 60000,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = "ExpertQuote loading-indicator wait compiled to an observable absent condition."
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0057-0068:0067",
            Sequence = 67,
            SourceStep = "0057-0068",
            SourceName = "search for the same quote and verify identity.",
            SourceXTestStep = "",
            SourceSentence = "the \"PreQualification\" screen heading should exist",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "PreQualification",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_BOP_Smoke_Test:0057-0068:0068",
            Sequence = 68,
            SourceStep = "0057-0068",
            SourceName = "search for the same quote and verify identity.",
            SourceXTestStep = "",
            SourceSentence = "the displayed \"Name and Quote\" text should exactly equal captured runtime value \"Quote_NameNum\"",
            Module = "",
            Operation = CanonicalOperation.Verify,
            Target = "Name and Quote",
            ValueExpression = "",
            ExpectedExpression = "{{runtime:Quote_NameNum}}",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyDictionary<string, IReadOnlyList<CanonicalAction>> AllStages { get; } =
        new Dictionary<string, IReadOnlyList<CanonicalAction>>(StringComparer.OrdinalIgnoreCase)
        {
            ["ClientAndAccount"] = ClientAndAccount,
            ["ProposalStart"] = ProposalStart,
            ["IdentityAndPrefill"] = IdentityAndPrefill,
            ["PreQualification"] = PreQualification,
            ["Verification"] = Verification,
        };
}
