using ToscaArtifactAutomation.Core.Canonical;

namespace ToscaArtifactAutomation.CLEQ.CanonicalMaps;

public static class EQSFPSmokeTestCanonicalMap
{
    public static IReadOnlyList<CanonicalAction> ClientAndAccount { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0029:0001",
            Sequence = 1,
            SourceStep = "0029",
            SourceName = "Set Buffer for Last Name",
            SourceXTestStep = "",
            SourceSentence = "I generate and retain a RANDOM value matching \"Smoke[a-z]{4}\" as runtime value \"LastName\"",
            Module = "EQ|Common|Enter Client Search Info",
            Operation = CanonicalOperation.GenerateRandom,
            Target = "",
            ValueExpression = "Smoke[a-z]{4}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "LastName",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0029:0002",
            Sequence = 2,
            SourceStep = "0029",
            SourceName = "Set Buffer for Last Name",
            SourceXTestStep = "",
            SourceSentence = "I generate and retain a RANDOM value matching \"SFP [a-z]{3}\" as runtime value \"FirstName\"",
            Module = "EQ|Common|Enter Client Search Info",
            Operation = CanonicalOperation.GenerateRandom,
            Target = "",
            ValueExpression = "SFP [a-z]{3}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "FirstName",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0030:0003",
            Sequence = 3,
            SourceStep = "0030",
            SourceName = "Client Info",
            SourceXTestStep = "",
            SourceSentence = "I wait until \"Client Info\" is visible",
            Module = "EQ|Common|Enter Client Search Info",
            Operation = CanonicalOperation.Wait,
            Target = "Client Info",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0030:0004",
            Sequence = 4,
            SourceStep = "0030",
            SourceName = "Client Info",
            SourceXTestStep = "",
            SourceSentence = "I wait until \"New/Existing Client Search\" is visible",
            Module = "EQ|Common|Enter Client Search Info",
            Operation = CanonicalOperation.Wait,
            Target = "New/Existing Client Search",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0030:0005",
            Sequence = 5,
            SourceStep = "0030",
            SourceName = "Client Info",
            SourceXTestStep = "",
            SourceSentence = "I use runtime value \"FirstName\" in \"customer.name.first\"",
            Module = "EQ|Common|Enter Client Search Info",
            Operation = CanonicalOperation.Input,
            Target = "customer.name.first",
            ValueExpression = "{{runtime:FirstName}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0030:0006",
            Sequence = 6,
            SourceStep = "0030",
            SourceName = "Client Info",
            SourceXTestStep = "",
            SourceSentence = "I use runtime value \"LastName\" in \"customer.name.last\"",
            Module = "EQ|Common|Enter Client Search Info",
            Operation = CanonicalOperation.Input,
            Target = "customer.name.last",
            ValueExpression = "{{runtime:LastName}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0030:0007",
            Sequence = 7,
            SourceStep = "0030",
            SourceName = "Client Info",
            SourceXTestStep = "",
            SourceSentence = "I use \"08/13/2004\" (one-iteration value for 08/13/2026; source rule: execution date minus 22 years) in \"customer.dateOfBirth\"",
            Module = "EQ|Common|Enter Client Search Info",
            Operation = CanonicalOperation.Input,
            Target = "customer.dateOfBirth",
            ValueExpression = "{{data:customer_dateofbirth_7}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0030:0008",
            Sequence = 8,
            SourceStep = "0030",
            SourceName = "Client Info",
            SourceXTestStep = "",
            SourceSentence = "I click \"Search\"",
            Module = "EQ|Common|Enter Client Search Info",
            Operation = CanonicalOperation.Click,
            Target = "Search",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0031:0009",
            Sequence = 9,
            SourceStep = "0031",
            SourceName = "Create New Client",
            SourceXTestStep = "",
            SourceSentence = "I wait until \"Existing Client Match\" exists",
            Module = "CL|EQ|Common|Create New Client",
            Operation = CanonicalOperation.Wait,
            Target = "Existing Client Match",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0031:0010",
            Sequence = 10,
            SourceStep = "0031",
            SourceName = "Create New Client",
            SourceXTestStep = "",
            SourceSentence = "I click \"Create New Client_1\"",
            Module = "CL|EQ|Common|Create New Client",
            Operation = CanonicalOperation.Click,
            Target = "Create New Client_1",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0031:0011",
            Sequence = 11,
            SourceStep = "0031",
            SourceName = "Create New Client",
            SourceXTestStep = "",
            SourceSentence = "I press TAB and click on \"Next\"",
            Module = "CL|EQ|Common|Create New Client",
            Operation = CanonicalOperation.Press,
            Target = "Next",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0032:0012",
            Sequence = 12,
            SourceStep = "0032",
            SourceName = "Set StateName Buffer",
            SourceXTestStep = "",
            SourceSentence = "runtime value \"StateName\" is set to \"Minnesota\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:statename}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "StateName",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0033:0013",
            Sequence = 13,
            SourceStep = "0033",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I wait until \"Account Information Header\" is visible",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Wait,
            Target = "Account Information Header",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0033:0014",
            Sequence = 14,
            SourceStep = "0033",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I leave \"Owner Middle Name\" blank and press TAB",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Press,
            Target = "Owner Middle Name",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0033:0015",
            Sequence = 15,
            SourceStep = "0033",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I enter a RANDOM value matching \"3[0-9]{9}\" in \"Owner Phone\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.GenerateRandom,
            Target = "Owner Phone",
            ValueExpression = "3[0-9]{9}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "OwnerPhone",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0033:0016",
            Sequence = 16,
            SourceStep = "0033",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I enter a RANDOM value matching \"test@[a-z]{4}\\\\.com\" in \"Owner Email\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.GenerateRandom,
            Target = "Owner Email",
            ValueExpression = "test@[a-z]{4}\\.com",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "OwnerEmail",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0034:0017",
            Sequence = 17,
            SourceStep = "0034",
            SourceName = "Account Details - Select Married",
            SourceXTestStep = "",
            SourceSentence = "I select \"Married\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Select,
            Target = "Married",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0035:0018",
            Sequence = 18,
            SourceStep = "0035",
            SourceName = "Navigate down the screen",
            SourceXTestStep = "",
            SourceSentence = "I press SHIFT+TAB on \"Street Address\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Press,
            Target = "Street Address",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:SHIFTTAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0036:0019",
            Sequence = 19,
            SourceStep = "0036",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I enter \"115 S Main ST\", then press TAB in \"Street Address\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Press,
            Target = "Street Address",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:ENTER", "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0036:0020",
            Sequence = 20,
            SourceStep = "0036",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I enter \"111\", then press TAB in \"Address 2\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Press,
            Target = "Address 2",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:ENTER", "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0036:0021",
            Sequence = 21,
            SourceStep = "0036",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I enter \"Warren\", then press TAB in \"City\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Press,
            Target = "City",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:ENTER", "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0036:0022",
            Sequence = 22,
            SourceStep = "0036",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I click on \"State Dropdown\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Click,
            Target = "State Dropdown",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0036:0023",
            Sequence = 23,
            SourceStep = "0036",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I select the retained representative state from the state list",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Select,
            Target = "State",
            ValueExpression = "{{runtime:StateName}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0036:0024",
            Sequence = 24,
            SourceStep = "0036",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I enter \"56762\", then press TAB in \"Zip\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Press,
            Target = "Zip",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:ENTER", "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0036:0025",
            Sequence = 25,
            SourceStep = "0036",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I wait until \"Map\" exists",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Wait,
            Target = "Map",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0036:0026",
            Sequence = 26,
            SourceStep = "0036",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I wait until \"Satellite\" exists",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Wait,
            Target = "Satellite",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0037:0027",
            Sequence = 27,
            SourceStep = "0037",
            SourceName = "Navigate down the screen",
            SourceXTestStep = "",
            SourceSentence = "I press SHIFT+TAB on \"Next\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Press,
            Target = "Next",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:SHIFTTAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0038:0028",
            Sequence = 28,
            SourceStep = "0038",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I select \"Have you received mail at this address for at least 90 days? Yes\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Select,
            Target = "Have you received mail at this address for at least 90 days? Yes",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0038:0029",
            Sequence = 29,
            SourceStep = "0038",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I select \"Is the account address also where the client resides? Yes\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Select,
            Target = "Is the account address also where the client resides? Yes",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0038:0030",
            Sequence = 30,
            SourceStep = "0038",
            SourceName = "Account Details - Account Info",
            SourceXTestStep = "",
            SourceSentence = "I click \"Next\"",
            Module = "EQ|Common|Enter Account Details - Account Info",
            Operation = CanonicalOperation.Click,
            Target = "Next",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyList<CanonicalAction> ProposalStart { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0031",
            Sequence = 31,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I wait until \"Proposal Details Header\" is visible",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Wait,
            Target = "Proposal Details Header",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0032",
            Sequence = 32,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I select \"Special Farm Package\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Select,
            Target = "Special Farm Package",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0033",
            Sequence = 33,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I enter \"12-01-2025\", then press TAB in \"Effective Date\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Press,
            Target = "Effective Date",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:ENTER", "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0034",
            Sequence = 34,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I set \"newAccountAddress\" to \"True\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Input,
            Target = "True",
            ValueExpression = "{{data:true_34}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0035",
            Sequence = 35,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I press TAB on \"PolicyTerm\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Press,
            Target = "PolicyTerm",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0036",
            Sequence = 36,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I enter \"12 months\" in \"PolicyTerm\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Input,
            Target = "PolicyTerm",
            ValueExpression = "{{data:policyterm_36}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0037",
            Sequence = 37,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I press TAB on \"PolicyTerm\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Press,
            Target = "PolicyTerm",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0038",
            Sequence = 38,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I press TAB on \"State Dropdown\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Press,
            Target = "State Dropdown",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0039",
            Sequence = 39,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I select the retained representative state from the state list",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Select,
            Target = "State",
            ValueExpression = "{{runtime:StateName}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0040",
            Sequence = 40,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I enter \"D2102\", then press TAB, then press TAB in \"AgentPC\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Press,
            Target = "AgentPC",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:ENTER", "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0041",
            Sequence = 41,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I capture \"Effective Date\" as runtime value \"EffDate\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Capture,
            Target = "Effective Date",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "InnerText",
            Alias = "EffDate",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0042",
            Sequence = 42,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I click on \"State Dropdown\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Click,
            Target = "State Dropdown",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0039:0043",
            Sequence = 43,
            SourceStep = "0039",
            SourceName = "Proposal Start",
            SourceXTestStep = "",
            SourceSentence = "I click \"Start Quote\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.Click,
            Target = "Start Quote",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0040:0044",
            Sequence = 44,
            SourceStep = "0040",
            SourceName = "Set Buffer for LOB",
            SourceXTestStep = "",
            SourceSentence = "runtime value \"LOB\" is set to \"SFP\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:lob}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "LOB",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0041:0045",
            Sequence = 45,
            SourceStep = "0041",
            SourceName = "Set Buffer for WaitOnTime",
            SourceXTestStep = "",
            SourceSentence = "runtime value \"WaitOnTime\" is set to \"5000\"",
            Module = "EQ|Common|Proposal Start",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:waitontime}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "WaitOnTime",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyList<CanonicalAction> IdentityAndPrefill { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0042:0046",
            Sequence = 46,
            SourceStep = "0042",
            SourceName = "SSN",
            SourceXTestStep = "",
            SourceSentence = "I wait until \"The SSN could not be found. Please enter an SSN.\" is visible",
            Module = "EQ|Common|SSN",
            Operation = CanonicalOperation.Wait,
            Target = "The SSN could not be found. Please enter an SSN.",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0042:0047",
            Sequence = 47,
            SourceStep = "0042",
            SourceName = "SSN",
            SourceXTestStep = "",
            SourceSentence = "I enter a RANDOM value consisting of fixed prefix \"025\", followed by 6 random digits in \"ssn\"",
            Module = "EQ|Common|SSN",
            Operation = CanonicalOperation.GenerateRandom,
            Target = "ssn",
            ValueExpression = "025[0-9]{6}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "InsuredSSN",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0042:0048",
            Sequence = 48,
            SourceStep = "0042",
            SourceName = "SSN",
            SourceXTestStep = "",
            SourceSentence = "I wait until \"Submit - Angular\" is visible",
            Module = "EQ|Common|SSN",
            Operation = CanonicalOperation.Wait,
            Target = "Submit - Angular",
            ValueExpression = "",
            ExpectedExpression = "Visible",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0042:0049",
            Sequence = 49,
            SourceStep = "0042",
            SourceName = "SSN",
            SourceXTestStep = "",
            SourceSentence = "I press TAB on \"Submit - Angular\"",
            Module = "EQ|Common|SSN",
            Operation = CanonicalOperation.Press,
            Target = "Submit - Angular",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0042:0050",
            Sequence = 50,
            SourceStep = "0042",
            SourceName = "SSN",
            SourceXTestStep = "",
            SourceSentence = "I click \"Submit - Angular\"",
            Module = "EQ|Common|SSN",
            Operation = CanonicalOperation.Click,
            Target = "Submit - Angular",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0043:0051",
            Sequence = 51,
            SourceStep = "0043",
            SourceName = "Verify if Popup exists",
            SourceXTestStep = "",
            SourceSentence = "if the No Prefill Match Found popup exists, \"No Prefill Match Found\" should exist",
            Module = "EQ|Common|SSN",
            Operation = CanonicalOperation.Verify,
            Target = "No Prefill Match Found",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "if the No Prefill Match Found popup exists",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0044:0052",
            Sequence = 52,
            SourceStep = "0044",
            SourceName = "Click Continue",
            SourceXTestStep = "",
            SourceSentence = "if the No Prefill Match Found popup exists, I click \"Continue\"",
            Module = "EQ|Common|SSN",
            Operation = CanonicalOperation.Click,
            Target = "Continue",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "if the No Prefill Match Found popup exists",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0045:0053",
            Sequence = 53,
            SourceStep = "0045",
            SourceName = "Set Buffer for WaitOnTime",
            SourceXTestStep = "",
            SourceSentence = "runtime value \"WaitOnTime\" is set to \"25000\"",
            Module = "EQ|Common|SSN",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:waitontime_2}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "WaitOnTime",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0046:0054",
            Sequence = 54,
            SourceStep = "0046",
            SourceName = "Buffer Screen Name",
            SourceXTestStep = "",
            SourceSentence = "runtime value \"Screen\" is set to \"Pre Qualification\"",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:screen}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "Screen",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyList<CanonicalAction> PolicyDetails { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0047:0055",
            Sequence = 55,
            SourceStep = "0047",
            SourceName = "Check if on Correct Screen",
            SourceXTestStep = "",
            SourceSentence = "if the current screen is not the required screen, \"Screen Heading\" should not exist",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.Verify,
            Target = "Screen Heading",
            ValueExpression = "",
            ExpectedExpression = "Absent",
            PropertyName = "",
            Alias = "",
            Condition = "if the current screen is not the required screen",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0048:0056",
            Sequence = 56,
            SourceStep = "0048",
            SourceName = "Navigate to Correct Screen",
            SourceXTestStep = "",
            SourceSentence = "if the current screen is not the required screen, I click the navigation link for runtime value \"Screen\"",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.Click,
            Target = "Screen",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "if the current screen is not the required screen",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0049:0057",
            Sequence = 57,
            SourceStep = "0049",
            SourceName = "EQ|Common|Review Required Pop-up",
            SourceXTestStep = "",
            SourceSentence = "if source condition \"'Review Required - Keep Going' == \\\"Yes\\\"\" is satisfied, I click \"Keep Going\"",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.Click,
            Target = "Keep Going",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "'Review Required - Keep Going' == \"Yes\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0050:0058",
            Sequence = 58,
            SourceStep = "0050",
            SourceName = "Buffer Screen Name",
            SourceXTestStep = "",
            SourceSentence = "runtime value \"Screen\" is set to \"Pre Qualification\"",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:screen}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "Screen",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0051:0059",
            Sequence = 59,
            SourceStep = "0051",
            SourceName = "Buffer Screen Name if different",
            SourceXTestStep = "",
            SourceSentence = "runtime value \"Screen\" is set to \"Pre-Qualification\"",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:screen_2}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "Screen",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0052:0060",
            Sequence = 60,
            SourceStep = "0052",
            SourceName = "EQ Loading Indicator Wait",
            SourceXTestStep = "",
            SourceSentence = "if the current screen is not the required screen, I wait until \"Loading ...\" does not exist",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.Wait,
            Target = "Loading ...",
            ValueExpression = "",
            ExpectedExpression = "Absent",
            PropertyName = "",
            Alias = "",
            Condition = "if the current screen is not the required screen",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0053:0061",
            Sequence = 61,
            SourceStep = "0053",
            SourceName = "Wait on for correct Screen",
            SourceXTestStep = "",
            SourceSentence = "if the current screen is not the required screen, I wait until \"Screen Heading\" exists",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.Wait,
            Target = "Screen Heading",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "if the current screen is not the required screen",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyList<CanonicalAction> Verification { get; } = new CanonicalAction[]
    {
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0054:0062",
            Sequence = 62,
            SourceStep = "0054",
            SourceName = "Quote Identifying",
            SourceXTestStep = "",
            SourceSentence = "I capture \"Name and Quote\" as runtime value \"Quote_NameNum\"",
            Module = "CL|EQ|Common|Quote Identifying and Close Quote",
            Operation = CanonicalOperation.Capture,
            Target = "Name and Quote",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "InnerText",
            Alias = "Quote_NameNum",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0055:0063",
            Sequence = 63,
            SourceStep = "0055",
            SourceName = "Set Buffer for quote num & id",
            SourceXTestStep = "",
            SourceSentence = "I set runtime value \"Quote_Num\" from RUNTIME-DERIVED value from \"{STRINGREPLACE[{B[Quote_NameNum]}][{B[LastName]}][]}\"",
            Module = "CL|EQ|Common|Quote Identifying and Close Quote",
            Operation = CanonicalOperation.Evaluate,
            Target = "",
            ValueExpression = "{STRINGREPLACE[{B[Quote_NameNum]}][{B[LastName]}][]}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "Quote_Num",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0055:0064",
            Sequence = 64,
            SourceStep = "0055",
            SourceName = "Set Buffer for quote num & id",
            SourceXTestStep = "",
            SourceSentence = "I set runtime value \"QuoteID\" from runtime value \"Quote_Num\"",
            Module = "CL|EQ|Common|Quote Identifying and Close Quote",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{runtime:Quote_Num}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "QuoteID",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0056:0065",
            Sequence = 65,
            SourceStep = "0056",
            SourceName = "Close Quote",
            SourceXTestStep = "",
            SourceSentence = "I click on \"Close Quote\"",
            Module = "CL|EQ|Common|Quote Identifying and Close Quote",
            Operation = CanonicalOperation.Click,
            Target = "Close Quote",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0057:0066",
            Sequence = 66,
            SourceStep = "0057",
            SourceName = "EQ Loading Indicator Wait",
            SourceXTestStep = "",
            SourceSentence = "I wait until \"Loading ...\" does not exist",
            Module = "CL|EQ|Common|Search by QuoteNum > CL|EQ|Common|WaitOn Loading Indicator",
            Operation = CanonicalOperation.Wait,
            Target = "Loading ...",
            ValueExpression = "",
            ExpectedExpression = "Absent",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0058:0067",
            Sequence = 67,
            SourceStep = "0058",
            SourceName = "Search by QuoteNum",
            SourceXTestStep = "",
            SourceSentence = "I use RUNTIME-DERIVED value from \"{SENDKEYS[{B[Quote_Num]}]}{TAB}{TAB}\" in \"quoteSearchInput\"",
            Module = "CL|EQ|Common|Search by QuoteNum",
            Operation = CanonicalOperation.Input,
            Target = "quoteSearchInput",
            ValueExpression = "{B[Quote_Num]}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = new[] { "POST:TAB", "POST:TAB" },
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0058:0068",
            Sequence = 68,
            SourceStep = "0058",
            SourceName = "Search by QuoteNum",
            SourceXTestStep = "",
            SourceSentence = "I click \"Search\"",
            Module = "CL|EQ|Common|Search by QuoteNum",
            Operation = CanonicalOperation.Click,
            Target = "Search",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0059:0069",
            Sequence = 69,
            SourceStep = "0059",
            SourceName = "EQ Loading Indicator Wait",
            SourceXTestStep = "",
            SourceSentence = "I wait until \"Loading ...\" does not exist",
            Module = "CL|EQ|Common|Search by QuoteNum > CL|EQ|Common|WaitOn Loading Indicator",
            Operation = CanonicalOperation.Wait,
            Target = "Loading ...",
            ValueExpression = "",
            ExpectedExpression = "Absent",
            PropertyName = "",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0060:0070",
            Sequence = 70,
            SourceStep = "0060",
            SourceName = "Buffer Screen Name",
            SourceXTestStep = "",
            SourceSentence = "runtime value \"Screen\" is set to \"Pre Qualification\"",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:screen}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "Screen",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0061:0071",
            Sequence = 71,
            SourceStep = "0061",
            SourceName = "Check if on Correct Screen",
            SourceXTestStep = "",
            SourceSentence = "if the current screen is not the required screen, \"Screen Heading\" should not exist",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.Verify,
            Target = "Screen Heading",
            ValueExpression = "",
            ExpectedExpression = "Absent",
            PropertyName = "",
            Alias = "",
            Condition = "if the current screen is not the required screen",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0062:0072",
            Sequence = 72,
            SourceStep = "0062",
            SourceName = "Navigate to Correct Screen",
            SourceXTestStep = "",
            SourceSentence = "if the current screen is not the required screen, I click the navigation link for runtime value \"Screen\"",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.Click,
            Target = "Screen",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "if the current screen is not the required screen",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0063:0073",
            Sequence = 73,
            SourceStep = "0063",
            SourceName = "EQ|Common|Review Required Pop-up",
            SourceXTestStep = "",
            SourceSentence = "if source condition \"'Review Required - Keep Going' == \\\"Yes\\\"\" is satisfied, I click \"Keep Going\"",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.Click,
            Target = "Keep Going",
            ValueExpression = "",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "",
            Condition = "'Review Required - Keep Going' == \"Yes\"",
            ConditionPolicy = ConditionPolicy.Expression,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0064:0074",
            Sequence = 74,
            SourceStep = "0064",
            SourceName = "Buffer Screen Name",
            SourceXTestStep = "",
            SourceSentence = "runtime value \"Screen\" is set to \"Pre Qualification\"",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:screen}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "Screen",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0065:0075",
            Sequence = 75,
            SourceStep = "0065",
            SourceName = "Buffer Screen Name if different",
            SourceXTestStep = "",
            SourceSentence = "runtime value \"Screen\" is set to \"Pre-Qualification\"",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.SetRuntime,
            Target = "",
            ValueExpression = "{{data:screen_2}}",
            ExpectedExpression = "",
            PropertyName = "",
            Alias = "Screen",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0066:0076",
            Sequence = 76,
            SourceStep = "0066",
            SourceName = "EQ Loading Indicator Wait",
            SourceXTestStep = "",
            SourceSentence = "if the current screen is not the required screen, I wait until \"Loading ...\" does not exist",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.Wait,
            Target = "Loading ...",
            ValueExpression = "",
            ExpectedExpression = "Absent",
            PropertyName = "",
            Alias = "",
            Condition = "if the current screen is not the required screen",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0067:0077",
            Sequence = 77,
            SourceStep = "0067",
            SourceName = "Wait on for correct Screen",
            SourceXTestStep = "",
            SourceSentence = "if the current screen is not the required screen, I wait until \"Screen Heading\" exists",
            Module = "EQ|Common|Navigate to Screen",
            Operation = CanonicalOperation.Wait,
            Target = "Screen Heading",
            ValueExpression = "",
            ExpectedExpression = "Exists",
            PropertyName = "",
            Alias = "",
            Condition = "if the current screen is not the required screen",
            ConditionPolicy = ConditionPolicy.OptionalTarget,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = true,
            ExternalKey = "",
            Notes = ""
        },
        new CanonicalAction
        {
            Id = "EQ_SFP_Smoke_Test:0068:0078",
            Sequence = 78,
            SourceStep = "0068",
            SourceName = "Quote Identifying",
            SourceXTestStep = "",
            SourceSentence = "\"Name and Quote\" property \"InnerText\" should equal runtime value \"Quote_NameNum\"",
            Module = "CL|EQ|Common|Verifying Quote",
            Operation = CanonicalOperation.Verify,
            Target = "Name and Quote",
            ValueExpression = "",
            ExpectedExpression = "{{data:expected_name_and_quote_innertext_78}}",
            PropertyName = "InnerText",
            Alias = "",
            Condition = "",
            ConditionPolicy = ConditionPolicy.Always,
            TimeoutMs = 0,
            Commands = Array.Empty<string>(),
            Optional = false,
            ExternalKey = "",
            Notes = ""
        },
    };

    public static IReadOnlyDictionary<string, IReadOnlyList<CanonicalAction>> AllStages { get; } =
        new Dictionary<string, IReadOnlyList<CanonicalAction>>(StringComparer.OrdinalIgnoreCase)
        {
            ["ClientAndAccount"] = ClientAndAccount,
            ["ProposalStart"] = ProposalStart,
            ["IdentityAndPrefill"] = IdentityAndPrefill,
            ["PolicyDetails"] = PolicyDetails,
            ["Verification"] = Verification,
        };
}
