using System.Text.Json; using System.Text.RegularExpressions;
namespace InsuranceAutomation.Core;
public sealed class ScenarioData {
 readonly Dictionary<string,string> _values=new(StringComparer.OrdinalIgnoreCase); readonly Dictionary<string,string> _runtime=new(StringComparer.OrdinalIgnoreCase); readonly Dictionary<string,(string Pattern,string Value)> _random=new(StringComparer.OrdinalIgnoreCase); readonly Dictionary<string,string> _external=new(StringComparer.OrdinalIgnoreCase);
 public string CurrentFile {get;private set;}=""; public bool IsLoaded=>CurrentFile.Length>0;
 public void Load(string file,string? externalFile=null){ _values.Clear();_runtime.Clear();_random.Clear();_external.Clear(); CurrentFile=file; using var d=JsonDocument.Parse(File.ReadAllText(file)); var r=d.RootElement; ReadObj(r,"application"); ReadObj(r,"dimensions"); ReadObj(r,"values"); if(r.TryGetProperty("random",out var rnd)) foreach(var p in rnd.EnumerateObject()){var pat=p.Value.TryGetProperty("pattern",out var q)?q.GetString()??"":"";_random[p.Name]=(pat,"");} if(externalFile!=null&&File.Exists(externalFile)){using var e=JsonDocument.Parse(File.ReadAllText(externalFile)); foreach(var p in e.RootElement.EnumerateObject()) _external[p.Name]=p.Value.GetString()??"";} }
 void ReadObj(JsonElement root,string name){if(!root.TryGetProperty(name,out var o)||o.ValueKind!=JsonValueKind.Object)return;foreach(var p in o.EnumerateObject())_values[p.Name]=p.Value.ValueKind==JsonValueKind.String?p.Value.GetString()??"":p.Value.ToString();}
 public string Get(string key,string fallback=""){ if(_runtime.TryGetValue(key,out var r))return r;if(_values.TryGetValue(key,out var v))return v;if(_external.TryGetValue(key,out var e)){if(e=="SYNTHETIC_REPLACE_ME"||string.IsNullOrWhiteSpace(e))throw new InvalidOperationException($"Replace synthetic/external test data key '{key}'.");return e;} return fallback;}
 public void Set(string key,string value)=>_runtime[key]=value;
 public string Random(string key,string pattern){if(_runtime.TryGetValue(key,out var v))return v; var p=string.IsNullOrWhiteSpace(pattern)&&_random.TryGetValue(key,out var rp)?rp.Pattern:pattern; v=RandomData.Generate(p);_runtime[key]=v;return v;}
 public string Resolve(string expr){ if(string.IsNullOrEmpty(expr))return ""; return Regex.Replace(expr,@"\{\{(data|runtime|external):([^}]+)\}\}",m=>Get(m.Groups[2].Value)); }
 public bool Condition(string expr){ if(string.IsNullOrWhiteSpace(expr))return true; expr=expr.Trim(); var op=expr.Contains("!=",StringComparison.Ordinal)?"!=":expr.Contains("==",StringComparison.Ordinal)?"==":""; if(op.Length==0)return true; var parts=expr.Split(new[]{op},2,StringSplitOptions.None); var key=parts[0].Trim().Trim('\"','\''); var right=parts[1].Trim().Trim('\"','\''); if(right.Equals("NULL",StringComparison.OrdinalIgnoreCase))right=""; var left=Get(key,key); var eq=string.Equals(left,right,StringComparison.OrdinalIgnoreCase); return op=="=="?eq:!eq; }
 public IReadOnlyDictionary<string,string> Snapshot(){var all=new Dictionary<string,string>(_values,StringComparer.OrdinalIgnoreCase);foreach(var p in _runtime)all[p.Key]=p.Value;if(all.ContainsKey("password"))all["password"]="***";return all;}
}
public static class RandomData { static readonly Random R=new(); public static string Generate(string pattern){pattern=(pattern??"").Trim('^','$'); var sb=new System.Text.StringBuilder(); for(int i=0;i<pattern.Length;){ if(pattern[i]=='\\'&&i+1<pattern.Length){sb.Append(pattern[i+1]);i+=2;continue;} if(pattern[i]=='['){var end=pattern.IndexOf(']',i);if(end<0){sb.Append(pattern[i++]);continue;}var cls=pattern[(i+1)..end];int count=1;var qm=Regex.Match(pattern[(end+1)..],@"^\{(\d+)\}");if(qm.Success){count=int.Parse(qm.Groups[1].Value);end+=qm.Length;}for(int j=0;j<count;j++)sb.Append(cls.Contains("A-Z")?(char)('A'+R.Next(26)):cls.Contains("a-z")?(char)('a'+R.Next(26)):(char)('0'+R.Next(10)));i=end+1;continue;} sb.Append(pattern[i++]);}return sb.ToString(); } }
