<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsTestProject>true</IsTestProject>
    <LangVersion>latest</LangVersion>
  <AssemblyName>ClientAutomation.PLDC.Tests</AssemblyName><RootNamespace>InsuranceAutomation</RootNamespace></PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright.NUnit" Version="1.61.0" />
    <PackageReference Include="Reqnroll.NUnit" Version="3.3.4" />
    <PackageReference Include="Reqnroll.Microsoft.Extensions.DependencyInjection" Version="3.3.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.1.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Features/**/*.feature" CopyToOutputDirectory="PreserveNewest" />
    <None Update="TestData/**/*.json" CopyToOutputDirectory="PreserveNewest" />
    <None Update="TestSuites/**/*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>