$ErrorActionPreference = 'Stop'
Push-Location (Join-Path $PSScriptRoot '..')
try {
    dotnet --version
    dotnet restore .\ToscaCanonicalSimple.sln
    if ($LASTEXITCODE -ne 0) { throw 'dotnet restore failed' }
    dotnet build .\ToscaCanonicalSimple.sln -c Debug --no-restore
    if ($LASTEXITCODE -ne 0) { throw 'dotnet build failed' }

    $playwright = Get-ChildItem -Path . -Filter playwright.ps1 -Recurse -File |
        Where-Object { $_.FullName -match '\\bin\\Debug\\net8\.0\\' } |
        Select-Object -First 1
    if (-not $playwright) { throw 'playwright.ps1 was not generated by the build' }
    & $playwright.FullName install chromium
    if ($LASTEXITCODE -ne 0) { throw 'Playwright browser installation failed' }

    Write-Host 'Setup complete. Configure config/framework.json and credential environment variables before execution.'
}
finally { Pop-Location }
