// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace InsuranceAutomation.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Auto Rate Filings Common Policy NB_Prior Eff Date")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("pl-dc")]
    [global::NUnit.Framework.CategoryAttribute("generated")]
    [global::NUnit.Framework.CategoryAttribute("auto-rate-filings-common-policy-nb-prior")]
    public partial class AutoRateFilingsCommonPolicyNB_PriorEffDateFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "pl-dc",
                "generated",
                "auto-rate-filings-common-policy-nb-prior"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Auto Rate Filings Common Policy NB_Prior Eff Date", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "auto-rate-filings-common-policy-nb-prior-eff-date.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/auto-rate-filings-common-policy-nb-prior-eff-date.feature.ndjson", 52);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Auto Rate Filings Common Policy NB_Prior Eff Date - <example>")]
        [global::NUnit.Framework.TestCaseAttribute("AL", "TestData/al-10.json", "AL", "08.08.2024", "American National Property And Casualty Co.", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("AR", "TestData/ar-10.json", "AR", "07.23.2025", "American National Property And Casualty Co.", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("AZ ANG", "TestData/az-ang-7.json", "AZ", "06.23.2025", "American National General Insurance Co.", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("AZ ANP", "TestData/az-anp-7.json", "AZ", "06.23.2025", "American National Property And Casualty Co.", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("CA", "TestData/ca-8.json", "CA", "08.08.2024", "American National Property And Casualty Co.", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("CO", "TestData/co-10.json", "CO", "08.08.2024", "American National Property And Casualty Co.", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("CT", "TestData/ct-8.json", "CT", "08.08.2024", "Farm Family Casualty Insurance Co.", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("DE", "TestData/de-10.json", "DE", "08.08.2024", "American National Property And Casualty Co.", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("GA", "TestData/ga-7.json", "GA", "08.08.2024", "American National Property And Casualty Co.", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("IA", "TestData/ia-10.json", "IA", "08.08.2024", "American National Property And Casualty Co.", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("ID", "TestData/id-10.json", "ID", "08.09.2025", "American National Property And Casualty Co.", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("IL", "TestData/il-10.json", "IL", "08.08.2024", "American National Property And Casualty Co.", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("IN", "TestData/in-10.json", "IN", "08.08.2024", "American National Property And Casualty Co.", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("KS", "TestData/ks-10.json", "KS", "08.08.2024", "American National Property And Casualty Co.", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("KY", "TestData/ky-10.json", "KY", "08.08.2024", "American National Property And Casualty Co.", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("MD", "TestData/md-8.json", "MD", "08.08.2024", "American National Property And Casualty Co.", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("ME", "TestData/me-10.json", "ME", "08.08.2024", "Farm Family Casualty Insurance Co.", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("MN", "TestData/mn-11.json", "MN", "08.08.2024", "American National Property And Casualty Co.", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("MO", "TestData/mo-12.json", "MO", "08.08.2024", "American National Property And Casualty Co.", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("MS", "TestData/ms-10.json", "MS", "08.08.2024", "American National Property And Casualty Co.", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("MT", "TestData/mt-10.json", "MT", "10.13.2025", "American National Property And Casualty Co.", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("ND", "TestData/nd-10.json", "ND", "08.08.2024", "American National Property And Casualty Co.", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("NE", "TestData/ne-11.json", "NE", "08.08.2024", "American National Property And Casualty Co.", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("NH", "TestData/nh-10.json", "NH", "08.08.2024", "Farm Family Casualty Insurance Co.", "23", null)]
        [global::NUnit.Framework.TestCaseAttribute("NJ", "TestData/nj-8.json", "NJ", "08.08.2024", "United Farm Family Insurance Co.", "24", null)]
        [global::NUnit.Framework.TestCaseAttribute("NM", "TestData/nm-10.json", "NM", "08.08.2024", "American National Property And Casualty Co.", "25", null)]
        [global::NUnit.Framework.TestCaseAttribute("NV", "TestData/nv-7.json", "NV", "08.08.2024", "American National General Insurance Co.", "26", null)]
        [global::NUnit.Framework.TestCaseAttribute("NY FFCIC", "TestData/ny-ffcic-7.json", "NY", "08.08.2024", "Farm Family Casualty Insurance Co.", "27", null)]
        [global::NUnit.Framework.TestCaseAttribute("NY UFFIC", "TestData/ny-uffic-7.json", "NY", "08.08.2024", "United Farm Family Insurance Co.", "28", null)]
        [global::NUnit.Framework.TestCaseAttribute("OH ANG", "TestData/oh-ang-7.json", "OH", "08.08.2024", "American National General Insurance Co.", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("OH ANP", "TestData/oh-anp-7.json", "OH", "08.08.2024", "American National Property And Casualty Co.", "30", null)]
        [global::NUnit.Framework.TestCaseAttribute("OK ANG", "TestData/ok-ang-7.json", "OK", "08.08.2024", "American National General Insurance Co.", "31", null)]
        [global::NUnit.Framework.TestCaseAttribute("OK ANP", "TestData/ok-anp-7.json", "OK", "08.08.2024", "American National Property And Casualty Co.", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("OR", "TestData/or-10.json", "OR", "08.08.2024", "American National Property And Casualty Co.", "33", null)]
        [global::NUnit.Framework.TestCaseAttribute("PA", "TestData/pa-8.json", "PA", "08.23.2025", "American National Property And Casualty Co.", "34", null)]
        [global::NUnit.Framework.TestCaseAttribute("RI", "TestData/ri-8.json", "RI", "08.08.2024", "Farm Family Casualty Insurance Co.", "35", null)]
        [global::NUnit.Framework.TestCaseAttribute("SC", "TestData/sc-10.json", "SC", "08.08.2024", "American National Property And Casualty Co.", "36", null)]
        [global::NUnit.Framework.TestCaseAttribute("SD ANG", "TestData/sd-ang-7.json", "SD", "08.08.2024", "American National General Insurance Co.", "37", null)]
        [global::NUnit.Framework.TestCaseAttribute("SD ANP", "TestData/sd-anp-7.json", "SD", "08.08.2024", "American National Property And Casualty Co.", "38", null)]
        [global::NUnit.Framework.TestCaseAttribute("TN ANG", "TestData/tn-ang-7.json", "TN", "08.08.2024", "American National General Insurance Co.", "39", null)]
        [global::NUnit.Framework.TestCaseAttribute("TN ANP", "TestData/tn-anp-7.json", "TN", "08.08.2024", "American National Property And Casualty Co.", "40", null)]
        [global::NUnit.Framework.TestCaseAttribute("TX", "TestData/tx-10.json", "TX", "08.08.2024", "American National County Mutual Insurance Co.", "41", null)]
        [global::NUnit.Framework.TestCaseAttribute("UT ANG", "TestData/ut-ang-7.json", "UT", "06.23.2025", "American National General Insurance Co.", "42", null)]
        [global::NUnit.Framework.TestCaseAttribute("UT ANP", "TestData/ut-anp-7.json", "UT", "06.23.2025", "American National Property And Casualty Co.", "43", null)]
        [global::NUnit.Framework.TestCaseAttribute("VA", "TestData/va-8.json", "VA", "08.08.2024", "American National Property And Casualty Co.", "44", null)]
        [global::NUnit.Framework.TestCaseAttribute("VT", "TestData/vt-8.json", "VT", "11.24.2025", "Farm Family Casualty Insurance Co.", "45", null)]
        [global::NUnit.Framework.TestCaseAttribute("WA", "TestData/wa-7.json", "WA", "08.08.2024", "American National Property And Casualty Co.", "46", null)]
        [global::NUnit.Framework.TestCaseAttribute("WI", "TestData/wi-11.json", "WI", "08.08.2024", "American National Property And Casualty Co.", "47", null)]
        [global::NUnit.Framework.TestCaseAttribute("WV", "TestData/wv-8.json", "WV", "08.08.2024", "American National Property And Casualty Co.", "48", null)]
        [global::NUnit.Framework.TestCaseAttribute("WY", "TestData/wy-10.json", "WY", "10.11.2025", "American National Property And Casualty Co.", "49", null)]
        public async global::System.Threading.Tasks.Task AutoRateFilingsCommonPolicyNB_PriorEffDate_Example(string example, string dataFile, string stateCode, string effectiveDate, string writingCompany, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("example", example);
            argumentsOfScenario.Add("dataFile", dataFile);
            argumentsOfScenario.Add("stateCode", stateCode);
            argumentsOfScenario.Add("effectiveDate", effectiveDate);
            argumentsOfScenario.Add("writingCompany", writingCompany);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Auto Rate Filings Common Policy NB_Prior Eff Date - <example>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync(string.Format("test data file \"{0}\" is loaded", dataFile), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.AndAsync(string.Format("the policy jurisdiction is \"{0}\"", stateCode), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.AndAsync(string.Format("the policy effective date is \"{0}\"", effectiveDate), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync(string.Format("the writing company is \"{0}\"", writingCompany), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
    await testRunner.GivenAsync("I prepare the Home and Auto application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
    await testRunner.AndAsync("I load the required business test data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.WhenAsync("I select or create the client and enter account details", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.AndAsync("I complete the proposal", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("I complete prequalification", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync("I enter driver information", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.AndAsync("I enter vehicle information", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.AndAsync("I assign drivers to vehicles", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.AndAsync("I enter claims and violation history", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync("I apply eligible discounts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.AndAsync("I select policy coverages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.AndAsync("I select additional coverages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
    await testRunner.AndAsync("I calculate and review pricing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.AndAsync("I complete underwriting information", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
    await testRunner.AndAsync("I enter additional interests", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.AndAsync("I enter billing details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
    await testRunner.AndAsync("I complete the submission", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync("I complete the launch checklist", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
    await testRunner.AndAsync("I validate downstream policy data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
    await testRunner.ThenAsync("I return to the submission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
    await testRunner.AndAsync("I verify the policy transmission confirmation", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.AndAsync("I save the generated business test results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
    await testRunner.AndAsync("I save and exit the submission", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
