// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace InsuranceAutomation.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Auto Rate Filings Common Policy NB")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("pl-dc")]
    [global::NUnit.Framework.CategoryAttribute("generated")]
    [global::NUnit.Framework.CategoryAttribute("auto-rate-filings-common-policy-nb")]
    public partial class AutoRateFilingsCommonPolicyNBFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "pl-dc",
                "generated",
                "auto-rate-filings-common-policy-nb"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Auto Rate Filings Common Policy NB", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "auto-rate-filings-common-policy-nb.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/auto-rate-filings-common-policy-nb.feature.ndjson", 52);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Auto Rate Filings Common Policy NB - <example>")]
        [global::NUnit.Framework.TestCaseAttribute("AL", "TestData/al-9.json", "AL", "ANPAC", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("AR", "TestData/ar-9.json", "AR", "ANPAC", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("AZ ANG", "TestData/az-ang-6.json", "AZ", "ANG", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("AZ ANP", "TestData/az-anp-6.json", "AZ", "ANPAC", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("CA", "TestData/ca-7.json", "CA", "ANPAC", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("CO", "TestData/co-9.json", "CO", "ANPAC", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("CT", "TestData/ct-7.json", "CT", "FFCIC", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("DE", "TestData/de-9.json", "DE", "ANPAC", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("GA", "TestData/ga-6.json", "GA", "ANPAC", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("IA", "TestData/ia-9.json", "IA", "ANPAC", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("ID", "TestData/id-9.json", "ID", "ANPAC", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("IL", "TestData/il-9.json", "IL", "ANPAC", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("IN", "TestData/in-9.json", "IN", "ANPAC", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("KS", "TestData/ks-9.json", "KS", "ANPAC", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("KY", "TestData/ky-9.json", "KY", "ANPAC", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("MD", "TestData/md-7.json", "MD", "ANPAC", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("ME", "TestData/me-9.json", "ME", "FFCIC", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("MN", "TestData/mn-10.json", "MN", "ANPAC", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("MO", "TestData/mo-11.json", "MO", "ANPAC", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("MS", "TestData/ms-9.json", "MS", "ANPAC", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("MT", "TestData/mt-9.json", "MT", "ANPAC", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("ND", "TestData/nd-9.json", "ND", "ANPAC", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("NE", "TestData/ne-10.json", "NE", "ANPAC", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("NH", "TestData/nh-9.json", "NH", "FFCIC", "23", null)]
        [global::NUnit.Framework.TestCaseAttribute("NJ", "TestData/nj-7.json", "NJ", "UFFIC", "24", null)]
        [global::NUnit.Framework.TestCaseAttribute("NM", "TestData/nm-9.json", "NM", "ANPAC", "25", null)]
        [global::NUnit.Framework.TestCaseAttribute("NV", "TestData/nv-6.json", "NV", "ANG", "26", null)]
        [global::NUnit.Framework.TestCaseAttribute("NY FFCIC", "TestData/ny-ffcic-6.json", "NY", "FFCIC", "27", null)]
        [global::NUnit.Framework.TestCaseAttribute("NY UFFIC", "TestData/ny-uffic-6.json", "NY", "UFFIC", "28", null)]
        [global::NUnit.Framework.TestCaseAttribute("OH ANG", "TestData/oh-ang-6.json", "OH", "ANG", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("OH ANP", "TestData/oh-anp-6.json", "OH", "ANPAC", "30", null)]
        [global::NUnit.Framework.TestCaseAttribute("OK ANG", "TestData/ok-ang-6.json", "OK", "ANG", "31", null)]
        [global::NUnit.Framework.TestCaseAttribute("OK ANP", "TestData/ok-anp-6.json", "OK", "ANPAC", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("OR", "TestData/or-9.json", "OR", "ANPAC", "33", null)]
        [global::NUnit.Framework.TestCaseAttribute("PA", "TestData/pa-7.json", "PA", "ANPAC", "34", null)]
        [global::NUnit.Framework.TestCaseAttribute("RI", "TestData/ri-7.json", "RI", "FFCIC", "35", null)]
        [global::NUnit.Framework.TestCaseAttribute("SC", "TestData/sc-9.json", "SC", "ANPAC", "36", null)]
        [global::NUnit.Framework.TestCaseAttribute("SD ANG", "TestData/sd-ang-6.json", "SD", "ANG", "37", null)]
        [global::NUnit.Framework.TestCaseAttribute("SD ANP", "TestData/sd-anp-6.json", "SD", "ANPAC", "38", null)]
        [global::NUnit.Framework.TestCaseAttribute("TN ANG", "TestData/tn-ang-6.json", "TN", "ANG", "39", null)]
        [global::NUnit.Framework.TestCaseAttribute("TN ANP", "TestData/tn-anp-6.json", "TN", "ANPAC", "40", null)]
        [global::NUnit.Framework.TestCaseAttribute("TX", "TestData/tx-9.json", "TX", "ANCMIC", "41", null)]
        [global::NUnit.Framework.TestCaseAttribute("UT ANG", "TestData/ut-ang-6.json", "UT", "ANG", "42", null)]
        [global::NUnit.Framework.TestCaseAttribute("UT ANP", "TestData/ut-anp-6.json", "UT", "ANPAC", "43", null)]
        [global::NUnit.Framework.TestCaseAttribute("VA", "TestData/va-7.json", "VA", "ANPAC", "44", null)]
        [global::NUnit.Framework.TestCaseAttribute("VT", "TestData/vt-7.json", "VT", "FFCIC", "45", null)]
        [global::NUnit.Framework.TestCaseAttribute("WA", "TestData/wa-6.json", "WA", "ANPAC", "46", null)]
        [global::NUnit.Framework.TestCaseAttribute("WI", "TestData/wi-10.json", "WI", "ANPAC", "47", null)]
        [global::NUnit.Framework.TestCaseAttribute("WV", "TestData/wv-7.json", "WV", "ANPAC", "48", null)]
        [global::NUnit.Framework.TestCaseAttribute("WY", "TestData/wy-9.json", "WY", "ANPAC", "49", null)]
        public async global::System.Threading.Tasks.Task AutoRateFilingsCommonPolicyNB_Example(string example, string dataFile, string stateCode, string writingCompany, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("example", example);
            argumentsOfScenario.Add("dataFile", dataFile);
            argumentsOfScenario.Add("stateCode", stateCode);
            argumentsOfScenario.Add("writingCompany", writingCompany);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Auto Rate Filings Common Policy NB - <example>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync(string.Format("test data file \"{0}\" is loaded", dataFile), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.AndAsync(string.Format("the policy jurisdiction is \"{0}\"", stateCode), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.AndAsync(string.Format("the writing company is \"{0}\"", writingCompany), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.GivenAsync("I prepare the Home and Auto application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
    await testRunner.AndAsync("I load the required business test data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
    await testRunner.WhenAsync("I select or create the client and enter account details", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.AndAsync("I complete the proposal", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.AndAsync("I complete prequalification", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("I enter driver information", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync("I enter vehicle information", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
    await testRunner.AndAsync("I assign drivers to vehicles", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.AndAsync("I enter claims and violation history", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
    await testRunner.AndAsync("I apply eligible discounts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
    await testRunner.AndAsync("I select policy coverages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
    await testRunner.AndAsync("I select additional coverages", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
    await testRunner.AndAsync("I calculate and review pricing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
    await testRunner.AndAsync("I complete underwriting information", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
    await testRunner.AndAsync("I enter additional interests", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 28
    await testRunner.AndAsync("I enter billing details", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
    await testRunner.AndAsync("I complete the submission", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
    await testRunner.AndAsync("I complete the launch checklist", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
    await testRunner.AndAsync("I validate downstream policy data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
    await testRunner.ThenAsync("I return to the submission", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
    await testRunner.AndAsync("I verify the policy transmission confirmation", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
    await testRunner.AndAsync("I save the generated business test results", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.AndAsync("I save and exit the submission", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
