// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace InsuranceAutomation.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Smoke Test Cycle")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("pl-dc")]
    [global::NUnit.Framework.CategoryAttribute("generated")]
    [global::NUnit.Framework.CategoryAttribute("smoke-test-cycle")]
    public partial class SmokeTestCycleFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "pl-dc",
                "generated",
                "smoke-test-cycle"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Smoke Test Cycle", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "smoke-test-cycle.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/smoke-test-cycle.feature.ndjson", 49);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Smoke Test Cycle - <example>")]
        [global::NUnit.Framework.TestCaseAttribute("AL", "TestData/al-5.json", "ALABAMA", "American National Property And Casualty Co.", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("AR", "TestData/ar-5.json", "ARKANSAS", "American National Property And Casualty Co.", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("AZ ANG", "TestData/az-ang-2.json", "ARIZONA", "American National General Insurance Co.", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("AZ ANP", "TestData/az-anp-2.json", "ARIZONA", "American National Property And Casualty Co.", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("CA", "TestData/ca-3.json", "CALIFORNIA", "American National Property And Casualty Co.", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("CO", "TestData/co-5.json", "COLORADO", "American National Property And Casualty Co.", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("CT", "TestData/ct-3.json", "CONNECTICUT", "Farm Family Casualty Insurance Co.", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("DE", "TestData/de-5.json", "DELAWARE", "American National Property And Casualty Co.", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("IA", "TestData/ia-5.json", "IOWA", "American National Property And Casualty Co.", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("ID", "TestData/id-5.json", "IDAHO", "American National Property And Casualty Co.", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("IL", "TestData/il-5.json", "ILLINOIS", "American National Property And Casualty Co.", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("IN", "TestData/in-5.json", "INDIANA", "American National Property And Casualty Co.", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("KS", "TestData/ks-5.json", "KANSAS", "American National Property And Casualty Co.", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("KY", "TestData/ky-5.json", "KENTUCKY", "American National Property And Casualty Co.", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("ME", "TestData/me-5.json", "MAINE", "Farm Family Casualty Insurance Co.", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("MD", "TestData/md-3.json", "MARYLAND", "American National Property And Casualty Co.", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("MN", "TestData/mn-6.json", "MINNESOTA", "American National Property And Casualty Co.", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("MO", "TestData/mo-7.json", "MISSOURI", "American National Property And Casualty Co.", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("MS", "TestData/ms-5.json", "MISSISSIPPI", "American National Property And Casualty Co.", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("MT", "TestData/mt-5.json", "MONTANA", "American National Property And Casualty Co.", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("ND", "TestData/nd-5.json", "NORTH DAKOTA", "American National Property And Casualty Co.", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("NE", "TestData/ne-6.json", "NEBRASKA", "American National Property And Casualty Co.", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("NH", "TestData/nh-5.json", "NEW HAMPSHIRE", "Farm Family Casualty Insurance Co.", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("NJ", "TestData/nj-3.json", "NEW JERSEY", "United Farm Family Insurance Co.", "23", null)]
        [global::NUnit.Framework.TestCaseAttribute("NM", "TestData/nm-5.json", "NEW MEXICO", "American National Property And Casualty Co.", "24", null)]
        [global::NUnit.Framework.TestCaseAttribute("NY FFCIC", "TestData/ny-ffcic-2.json", "NEW YORK", "Farm Family Casualty Insurance Co.", "25", null)]
        [global::NUnit.Framework.TestCaseAttribute("NY UFFIC", "TestData/ny-uffic-2.json", "NEW YORK", "United Farm Family Insurance Co.", "26", null)]
        [global::NUnit.Framework.TestCaseAttribute("OH ANG", "TestData/oh-ang-2.json", "OHIO", "American National General Insurance Co.", "27", null)]
        [global::NUnit.Framework.TestCaseAttribute("OH ANP", "TestData/oh-anp-2.json", "OHIO", "American National Property And Casualty Co.", "28", null)]
        [global::NUnit.Framework.TestCaseAttribute("OK ANG", "TestData/ok-ang-2.json", "OKLAHOMA", "American National General Insurance Co.", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("OK ANP", "TestData/ok-anp-2.json", "OKLAHOMA", "American National Property And Casualty Co.", "30", null)]
        [global::NUnit.Framework.TestCaseAttribute("OR", "TestData/or-5.json", "OREGON", "American National Property And Casualty Co.", "31", null)]
        [global::NUnit.Framework.TestCaseAttribute("PA", "TestData/pa-3.json", "PENNSYLVANIA", "American National Property And Casualty Co.", "32", null)]
        [global::NUnit.Framework.TestCaseAttribute("RI", "TestData/ri-3.json", "RHODE ISLAND", "Farm Family Casualty Insurance Co.", "33", null)]
        [global::NUnit.Framework.TestCaseAttribute("SC", "TestData/sc-5.json", "SOUTH CAROLINA", "American National Property And Casualty Co.", "34", null)]
        [global::NUnit.Framework.TestCaseAttribute("SD ANG", "TestData/sd-ang-2.json", "SOUTH DAKOTA", "American National General Insurance Co.", "35", null)]
        [global::NUnit.Framework.TestCaseAttribute("SD ANP", "TestData/sd-anp-2.json", "SOUTH DAKOTA", "American National Property And Casualty Co.", "36", null)]
        [global::NUnit.Framework.TestCaseAttribute("TN ANG", "TestData/tn-ang-2.json", "TENNESSEE", "American National General Insurance Co.", "37", null)]
        [global::NUnit.Framework.TestCaseAttribute("TN ANP", "TestData/tn-anp-2.json", "TENNESSEE", "American National Property And Casualty Co.", "38", null)]
        [global::NUnit.Framework.TestCaseAttribute("TX", "TestData/tx-5.json", "TEXAS", "American National County Mutual Insurance Co.", "39", null)]
        [global::NUnit.Framework.TestCaseAttribute("UT ANG", "TestData/ut-ang-2.json", "UTAH", "American National General Insurance Co.", "40", null)]
        [global::NUnit.Framework.TestCaseAttribute("UT ANP", "TestData/ut-anp-2.json", "UTAH", "American National Property And Casualty Co.", "41", null)]
        [global::NUnit.Framework.TestCaseAttribute("VA", "TestData/va-3.json", "VIRGINIA", "American National Property And Casualty Co.", "42", null)]
        [global::NUnit.Framework.TestCaseAttribute("VT", "TestData/vt-3.json", "VERMONT", "Farm Family Casualty Insurance Co.", "43", null)]
        [global::NUnit.Framework.TestCaseAttribute("WI", "TestData/wi-6.json", "WISCONSON", "American National Property And Casualty Co.", "44", null)]
        [global::NUnit.Framework.TestCaseAttribute("WV", "TestData/wv-3.json", "WEST VIRGINIA", "American National Property And Casualty Co.", "45", null)]
        [global::NUnit.Framework.TestCaseAttribute("WY", "TestData/wy-5.json", "WYOMING", "American National Property And Casualty Co.", "46", null)]
        public async global::System.Threading.Tasks.Task SmokeTestCycle_Example(string example, string dataFile, string stateCode, string writingCompany, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("example", example);
            argumentsOfScenario.Add("dataFile", dataFile);
            argumentsOfScenario.Add("stateCode", stateCode);
            argumentsOfScenario.Add("writingCompany", writingCompany);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Smoke Test Cycle - <example>", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync(string.Format("test data file \"{0}\" is loaded", dataFile), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
    await testRunner.AndAsync(string.Format("the policy jurisdiction is \"{0}\"", stateCode), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.AndAsync(string.Format("the writing company is \"{0}\"", writingCompany), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
    await testRunner.GivenAsync("I prepare the Home and Auto application", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 12
    await testRunner.AndAsync("I load the required business test data", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
    await testRunner.AndAsync("I set TCName", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.WhenAsync("I select or create the client and enter account details", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.AndAsync("I complete the proposal", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("I complete prequalification", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
    await testRunner.ThenAsync("I save the generated business test results", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
